apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: grafana-backup

spec:
  templates:
    - name: run
      nodeSelector:
        kubernetes.io/hostname: sce312.tokyotech.org

      volumes:
        - name: scripts
          configMap:
            name: backup-scripts
            defaultMode: 0755
        - name: keys
          secret:
            secretName: backup-keys

      container:
        name: backup
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
        imagePullPolicy: Always
        command:
          - /scripts/backup-grafana.sh
        volumeMounts:
          - mountPath: /scripts
            name: scripts
          - mountPath: /keys
            name: keys
        env:
          - name: DB_HOST
            value: tailscale.kmbk.tokyotech.org
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: service_grafana
          - name: DB_USER
            value: service_grafana
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-secrets
                key: db-password

      tolerations:
        - key: monitor-node
          operator: Equal
          value: "true"
          effect: NoSchedule
