apiVersion: v1
kind: Secret
metadata:
    name: litellm-fireworks-api-key
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    FIREWORKS_API_KEY: ENC[AES256_GCM,data:2mqcYzTmc1RCyRsw4tGR3nChrwWUKXOdIw==,iv:zDsfSJihcZdKi2Me14UgEy+Tcvl4RIoJOk4uE0Ew+VE=,tag:erj2ZDOOnxZRXWDrQpJXCw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MWl5MDB3d3UxZW5LV3h0
            bGhSS0FrNmI3d0E2QTdTT21yMEFrQnMzaG53CkJ4dWxmTFdHdlp4Mmo1aVlxYWZN
            RzV5Z0k4UUJKcW9mVkIzMHA2SVRBcVUKLS0tIDVYRTNZYVY5Z0haNUZsYVlhY1lI
            UFBQZHlhRytNZGtHK2ZUTmdoVFhMREkKFsyjFbpFc+l4l1gU4nCl/4hNXAb/Iuia
            nVRw9W3YOJeJHLrsDGqdS1/UbUj5FRoie14AVndveswNN11xSPYwFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T00:28:44Z"
    mac: ENC[AES256_GCM,data:KWnedjwzd/HB1xOgrXN2chHWLamTzteOH8P/kvf4G7QkH6Wbzeckb19FCG3GgCI0XW/qs5a73Xg0EK7yNoe0RU5zShPH81JZ1ocG9Ob27n0jc1BVPR7DbzSaEGlTBUZGR6rPDaKQqymCF1xvtEJVwc6JRavv6hL/q/54PiATAhc=,iv:OTGLAC01szbsyJkNxVhGPlUvCLx4ehrdV+3dnaPvrB8=,tag:ujxpWSxOJ07LD7hHCuUTOg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
