apiVersion: v1
kind: Secret
metadata:
    name: fireworks-api-key
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    FIREWORKS_API_KEY: ENC[AES256_GCM,data:5Bwv6pVHKxdALL+PW1hmDj6Uou3iqkGvNA==,iv:L7crlpSSPY7Sg5m6b3ymoeRi0MimYVHOdgOSDMEV58Q=,tag:AwXY9EXJ4iOTFo7FloIu+g==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQUpXN3FObmZXL0VJTkps
            WDVTQUplczhhbmNIamJITDJSY1ExRzJwVkNVCitEYkpKa3M1R1hhcjg2cVRxbExY
            d0VRVElyL01Od0dBa0trWDY5RFQ3SmMKLS0tIDNWMkFZbGd3Q21rU1EwNHhpMCt1
            VnZ3RVRXb0xpRUxHY3lST0JFQ1VsQzQKRbgRKbh9A0ejSIqsZ+i3EBGA0vgRgI2b
            FiW/xaMw9J6s7al+h85r2pmM0hGCYGWWnbEd34aAcbimWsRRWOo0Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T23:23:48Z"
    mac: ENC[AES256_GCM,data:IMNfQWQ8Wb04W4PwtdP3UzgvVdG1jseoq4ZWJ4BuM4x6kOVb/5c/xnPRZOp9xLnGuw8EyF8ejwF9891geNEgerI0P/90TtOnLPjQH/RzXSsky8eJDipEMnMVBOk7QKupg3vsaEmJRta4/ZbQLXiZwQsoBo01fAVcpVCm9/b3u1I=,iv:beIlfxV1ICJ0xFebKOZkK2TdetmEmyPJiWY+iJVWOQo=,tag:GzzgoRLXOccMYdGqJNJbGA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
