apiVersion: v1
kind: Secret
metadata:
    name: postgres-config
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:5kwruJJJx/PQF1F8cyDdvZTPZiqIrDclHfIvZiQ7sITLJl3dsge2LyLplnMXrg1iyb8neW27hJ2bazYn5zn9cC15C08dcqi49ieQYYNM8f524jVy7X0Gi1NEzfwseI7GQqZb9vK6wbx8clUuaBpr4CayF3lO+plyCSjnC5PV61DmIsBbxKz1BH2XgPY=,iv:6XjwJIbg1Ftu5I9ylmg2spPdOmEy0FhETMr7ZYbszd0=,tag:QrroAggPJjXVUYxgS34law==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWlFxWTQ5MldlSGgwcDFZ
            N2dFMTBvRFZOQS81TkRqNlRjOEpKVnlPUjFZCjVtQk1BdlBzOTA2T3NxWlMxUVRK
            VUxIRXFTc2lyOTgweXJrQUlUNnhraGsKLS0tIHhoWCt2UlNuSlY2ZDlxT3gwVTY5
            eDQzSkh0YjFUMDVCTDMraGcvN3l6V0EKB19oJnjAsEHbclpItAJ8DjaUAnKaee4E
            BDN85t2dsKQdADce4I5Mxtt6pfVZClMD+1tmlagKj5FCdGTW3XQOgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T15:32:15Z"
    mac: ENC[AES256_GCM,data:UDLtN2yZF9IP7MfjEX9yZaNWbUuLuUzm7dLtbygKSuDkTYqVi2Iik61UFyGfl6YvBDtX/Kycn81a96AUAt1CJ8M1CVhI9GRCOOTpSiNxYmZ5Padw3aYfufJG/P10uXE6Lz5v1Hz2GROoXGWxtyZrojVX4sMlhGcOfH+UQnBI4KA=,iv:Mdn7OJbVaTj4Q6rvMJQwXRcTozo8JefgxJf4xBcgrKk=,tag:8GFKgrwbfi+ItAemODs6NQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
