apiVersion: v1
kind: Secret
metadata:
    name: room-vpn-credential
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:Rfmly4lIXD3uPqOAan5d2YsznZepSKE5B7vTvZN1hkRoM1XS5+VGHbgTRCI6plx6AVhGz0p0k5fDW7LHJAbmt4WIsI0I0OiVVaXLXLPn4T9REhH0pvOnfw==,iv:J6YT6Xu51l9B+JiUjHDoSWJMOffRl0pgKF2760WfNKk=,tag:j4yXMm1lPQDjJcGNvvO5/A==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ3NoMktKeTd6OVA2VjZM
            eCs3VGJETy9IYU03ckZBdmR2TDhRTzYrWWhnClF3bGMrRzJiU0taMnNSQlE1UmtU
            Z29UaUZMY1UyaGlkbkVhcVBodVFDZVEKLS0tIEY5UzYwbW5IbzltUDA0Nk0rUFZy
            UTRTQmVHRWlYYlpCMUFDaUVLYWRMU3cK5K+E28xnjAvjavTFPiDYJ+mhJDA7cv6x
            ZnzIJEOhqSydYYQBPHk4Y1zF5Svbi5OLqXG87KBprexHeW6eV820Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T06:05:48Z"
    mac: ENC[AES256_GCM,data:tGuEq2OROkoXxrjpKNbefxukj+fyM2PJ198jzYIlAoxu8avZ2vo645G5ZWJhul4G542BxYn0PtP8adhE0SpxmeTkaEnN+/rMfMwQ2nEgPG7e1G/g4DUsNQuMQbZN/f+n6oetZz9GDeNdYO9J5WLEGqfhJpSrxFrUyM/QufelvNY=,iv:wneTtfpVRyiI67F/jXb1iOdIEY29MQLut1WyfkUl46U=,tag:pU/v5pJ2c0Y1Ikweikk7iw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
