resources:
  - backend
  - es
  - frontend
  - system-bot
  - widget
  - certificate
  - update-notification

replacements:
  - source:
      kind: Deployment
      name: traq-backend
      fieldPath: spec.template.spec.containers.[name=traq-backend].image
    targets:
      - select:
          kind: Job
          name: traq-update-notification
        fieldPaths:
          - spec.template.spec.containers.[name=notify].env.[name=TARGET_IMAGE].value
