apiVersion: v1
kind: Secret
metadata:
    name: anke-to
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    MARIADB_PASSWORD: ENC[AES256_GCM,data:l1RNW8SnhdOIm4BWccCX2PqonNrNmV5fPjiIUnyJ1Rc=,iv:JpVxKaL2DUrAE9uduw2hdpBQAoiLAOAf8K53IdxGWXE=,tag:eDlvBZ5WdoHaz6CLTtkaQQ==,type:str]
    TRAQ_WEBHOOK_SECRET: ENC[AES256_GCM,data:UC+R671YbFJNeB3q2w==,iv:iS+lTRlZQ2m2N4Ko46yU8oRREIXU2q/9dk5xL3e3Ypo=,tag:jjCJ3MYHEqWcYLyURUc+3A==,type:str]
    TRAQ_WEBHOOK_ID: ENC[AES256_GCM,data:HCDX9RJq2ohmVn50yiJAB1ijDVrYHJ5Z05skssOCpyv5jUj7,iv:v279eGbWUuWvxqC3DwfqRb8sDmFP+BEukwn9SIaYkuI=,tag:K0ZCSbktoVcyLD2uE/z7ow==,type:str]
    TRAQ_BOT_TOKEN: ENC[AES256_GCM,data:HAGNZpgfyg3qKgkg9NIzLqjKER2p1BA9E13bk5L58p6/nq+j,iv:Ktb/9+pkpWsbtP0afIxNQRfO7ZQEHAgQsR+0FYpGwJY=,tag:c7vmLMZM61cYCshaWqEP6A==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S0RzTm5UWjNlWXAranVE
            VHRXMjhvL1JBS2E4cFY1SGNGazREY3M1K0NZCndySnQ0R0RYdHNmaFFMMm1RaHpR
            Nm1TVFNIelRQQ3BDK3J3WW9naXBYSFEKLS0tIHRFSGozOVlOT0QvaU5sWHI4eVZC
            a3RiU3dZeUJJVzRuVmJMSlVzYTFPMjgKUqNXQ/t2DWyUHaQISlyVvGTQMdi3OeVY
            mOXEgSknRed6I22UlZC36wtPN15+ehr0pcvcLceIcbK+3AGoWNQiJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T06:51:04Z"
    mac: ENC[AES256_GCM,data:+z2evCzQwEWQA5U1s0bKBqKvL0gZWFTxCHw79JTfrVy3JSF8B15zctzDT2kbjbUnj/F/98RMrYf92exq0fA6SHkQ4EC8vKKXlm0XwrCUsVeOsS53LoR/wXC8Gq4G63dQwa6Qf2zWVF3SCmE4YbtmViT1wfDrYKHv7L1FfJV01Xo=,iv:gGLplGQOW5dzMJ3W9yUqHTkEEt+J7ydD+5fv3MAwCW8=,tag:Bx1GyiREvPZJEa+qt453vw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
