apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cpctf-maint

resources:
  - deploy.yaml
  - svc.yaml
  - ingress-route.yaml
  - certificate.yaml

configMapGenerator:
  - name: cpctf-maintenance-page
    namespace: cpctf-maint
    files:
      - config/index.html
      - config/default.conf
