apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy.yaml
  - svc.yaml
  - ingressroute.yaml
configMapGenerator:
  - name: cpctf-maintenance-page
    files:
      - config/index.html
      - config/default.conf
