helmGlobals:
  chartHome: ../.common

configMapGenerator:
  - name: preview-traq-config
    namespace: preview-traq
    files:
      - config.json=../traq/frontend/config.jsonc
    options:
      disableNameSuffixHash: true

helmCharts:
  - includeCRDs: true
    name: preview-ui
    namespace: preview-traq
    releaseName: preview-traq
    valuesFile: values.yaml
