mode: dev-and-prod

repo:
  owner: traPtitech
  repo: traQ_S-UI

webhook:
  name: traq-preview

tls:
  secretName: preview-traq-tls

host:
  base: traq-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/traq-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api`) || PathPrefix(`/.well-known`)
  service:
    kind: Service
    namespace: 'traq{{ if eq . "dev" }}-dev{{ end }}'
    name: traq-backend
    port: 8001
    scheme: http
    weight: 1

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/traq-ui:master@sha256:ef23247c9c5a64ed3bca2b1d5056c7c39e047f7a641f678a3f87221cb4ca4935"

otherParameters:
  port: 80
