[tools]
age = "latest"
ksops = "latest"
kubeconform = "latest"
kustomize = "latest"
prettier = "latest"
sops = "latest"
uv = "latest"
yamllint = "latest"

[env]
_.python.venv = ".venv"

[tasks.setup-crd]
dir = "{{config_root}}"
description = "CRD JSONスキーマを初期化"
run = '''
  .scripts/setup-crd.sh
'''

[tasks.build]
dir = "{{cwd}}"
usage = '''
  arg "<dir>" help="対象ディレクトリ" default="."
'''
run = '''
  kustomize build "${usage_dir?}" --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone --enable-helm
'''

[tasks.fmt]
dir = "{{cwd}}"
usage = '''
  arg "<dir>" help="対象ディレクトリ" default="."
'''
run = '''
  prettier --write "${usage_dir?}"
'''

[tasks.lint]
dir = "{{cwd}}"
usage = '''
  arg "<dir>" help="対象ディレクトリ" default="."
'''
run = '''
  yamllint "${usage_dir?}"
'''

[tasks.check]
dir = "{{config_root}}"
usage = '''
  arg "<dir>" help="対象ディレクトリ" default="."
'''
run = '''
  kubeconform \
    -schema-location default \
    -schema-location '{% raw %}.crd/{{ .Group }}-{{ .ResourceKind }}-{{ .ResourceAPIVersion }}.json{% endraw %}' \
    -skip apiextensions.k8s.io/v1/CustomResourceDefinition \
    "${usage_dir?}"
'''
