apiVersion: v1
kind: Secret
metadata:
    name: pyroscope-s3-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    s3-access-key: ENC[AES256_GCM,data:/nAf/z+AZDE+5AsAUcTciLERuJ4=,iv:rEHgZpsi26qWXdjTI/i96niaVK8uoU8Vl+bGlEPLE2k=,tag:tHiV3Axz2zrALzgp/1JKlA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:dKArzmnaFz3l5l0hGrFB9DHlbsw7DifsU0r9bkWT6/sSjuo5PD0xqw==,iv:cBAJIWERakUliojj68dfuaec4AghKfL2Ole6ikvYgl4=,tag:LnlLxjjx2EYv33LtqRYJwQ==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQnpYcU9jT3NlMWd0Umhs
            V0IzWGt0Ujh5TWp5d2UzVVJXMjBVeGd6Z0NFCmd1VzlNQnJFclA0TUJjUE8wd05j
            eWJhbFFmcDB2RDFxeW4zWjZ6dXdTRW8KLS0tIEUvWnZ1alhVREdybTl4Yi9zOGp0
            cFh6UGl4VmRZQ2trV0Z0OUluVnk2ODQKFUQnWdcKGD8eS7hM3wf3lEElhUmaWVBm
            3jHffvIW9ks5m6DLCjCuthSlwgzWqluw6HWCb/wZ4dEqGnxhxwZbUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T12:49:53Z"
    mac: ENC[AES256_GCM,data:Rl8HC+MZMhu1H+QQdI7XptSAaf32T3L7UMyX3gDQjzqOCXNpkHSAuo9NAz06WYwWJWRAX0LCXJabHXuYjjDxtJieM5zUcvDCpy6TdPGuH01riXNVpHxvgUhBaAh0WqmsOrIlM+oGfyPzXo9zc+hWhzzbyMpd1IdZPxCwEjrReSY=,iv:KXu854Sa+scyPBxnrh/VI3cDfBxP1hAFP0dwugj6I40=,tag:oQq8m1f2m8FBC3DQwiIfag==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
