apiVersion: v1
kind: Secret
metadata:
    name: tailscale-credential
    annotations:
        # kustomizeによってSecret名にhash suffixを付けさせる設定
        # Secretの中身が変更されたとき、自動リロードが可能になる
        # kustomize設定のnameReferenceで、Secretを読む側のフィールドを参照する必要あり
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    TS_AUTH_KEY: ENC[AES256_GCM,data:BXCoABQTQuHcOHYRoFntOX3+co6WJ87yBNqkWQcX7DrRG3tglC0Hui5UZ2mt9goF1RqRltD8fJZVtBgIKco=,iv:5zxvql00gcCBujCnjN2Ds/wMnQYEmMOLxGTesuc8Z14=,tag:NS/QuNTn72TfuvGFPELyog==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRmYyYWhOU1JRbHJDWUlw
            RFk0S2o1cmVoaThFRGZCMngyU1IrNnJyTmx3CnBZRjJxdGMzU0NjaGQ3MlFWRnFM
            WWs2dCtxckNPeTNIWUVuT2VsNURpQ1kKLS0tIERmVEpsRTBtNm1qOXZOcVFLb1pw
            WVorWm92RUxWS2QyVThENG1Nd2pxS1EKc+p+Rv4NS/VMcqdFuqWzHewFqZ9fFmdp
            nXq7LSukMBVnPO0trC3e6Ipv6aH3Yfxa9csezJnOb5rMmSSZm0XmAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T03:23:19Z"
    mac: ENC[AES256_GCM,data:KGE1ByjMvoBw+xFxLzosid70mKicQdL8vlkl5Er+aFE6lPBguSHh2WOTIatcj4ozTNf7WZ3hes1lVWOBgZ9dUdGy8Rcionny6nBHYYXYiYJqw0jfUNPtGguNnzpd5rqzJb2mK+/JBa81v4ZFUI/rE2OovcC3DjlJYRwGTHIn8/k=,iv:9h5KZYCCW5Go6ryDswMPg9R/sxRVX7zrhn5V0emJCQA=,tag:KX15L8yER6QWIF8YliBvOw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
