apiVersion: v1
kind: Secret
metadata:
    name: tailscale-credential
    annotations:
        # kustomizeによってSecret名にhash suffixを付けさせる設定
        # Secretの中身が変更されたとき、自動リロードが可能になる
        # kustomize設定のnameReferenceで、Secretを読む側のフィールドを参照する必要あり
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    TS_AUTH_KEY: ENC[AES256_GCM,data:ti63lJH8WpIj29t6XxfQnCbkDiddhXNJAUQyBcANLj084WcDoRvhqGmcJuhvSJUtMbw3+nWXWjkB5/ZGa78=,iv:6YDiyCHJ4tNlKWbcManz5CaQUVstIsgSdkuGTxeHYOc=,tag:y8N7+qGS5ApRrU99Fu88sg==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRmYyYWhOU1JRbHJDWUlw
            RFk0S2o1cmVoaThFRGZCMngyU1IrNnJyTmx3CnBZRjJxdGMzU0NjaGQ3MlFWRnFM
            WWs2dCtxckNPeTNIWUVuT2VsNURpQ1kKLS0tIERmVEpsRTBtNm1qOXZOcVFLb1pw
            WVorWm92RUxWS2QyVThENG1Nd2pxS1EKc+p+Rv4NS/VMcqdFuqWzHewFqZ9fFmdp
            nXq7LSukMBVnPO0trC3e6Ipv6aH3Yfxa9csezJnOb5rMmSSZm0XmAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T05:02:09Z"
    mac: ENC[AES256_GCM,data:14WSlKwHcKbTXYN/JADfgXf70QzaJttXziUx6gF1C4tfR687mkDCmm8OnX7XI/gySdwN/D79oFv2Wh1/f1cb+rCYE7O482cKWn6pvYTSbjTJQGmpNXXQDfaFa/SwyFwhsFuoCoM5c2NIVQuNLZcFwOrf+hHWr8CLoq6+aG5bz9Y=,iv:EHyzfiMzeODf0UUg/B/ol7tghe8mh7tS6gkHIYSllIs=,tag:PsgpQimnouEQSoQ66jVTNA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
