apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:tpKvbnGxeavMfpLQftKV9OUKDP1budmhV/EK5Xkhydo=,iv:tdiSdy+/UnqjGPzS6Hhi6JboJujWZ2QPY7AjYw42n2g=,tag:eeLEJbCcLVbmNylg7JHNeg==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWENjRG95eWtFQXRaOVd4
            OVVhdDB1L3UwczIveEhUQ3VHSEhKcTlzR1hnCjVkeUNrY1d6UTlHMEZwelVNYUcy
            ZlVGL2JjRkJhWEkwVCt2ajJVQzR6R1UKLS0tIFFsOHBRbGFtU3V3cXZzSnptRHFo
            MSt2R29FSHNTdHF6Tyt5MHNmMjZlbDQK+OsQaFllLwJ1TtEBNz7d5vLK6X3axyad
            oRNsyEf5IugCpqqdXMTGZijsDsrMq5vL37lDWuIntsdWKcuOD2ReWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T16:54:03Z"
    mac: ENC[AES256_GCM,data:cBB5E981WmZBgw4Hu2WOSpJIRASpX3J0hybc0aVEj2mwbyk2HWAqONN08M1foc9B16KO/OYyDj7E3snLYKvEsJ5+/nYpsWTZZVgHeFEXB/2EABFF/S+QCaPyoAB/hwybeoISgRygdBFNBZA8NtuG/vP+Xsbn5bMZmottZ25mD1k=,iv:aRmVarLwIAbgALuDHWDN0ro84tuIsCk46NtK5i6rNrQ=,tag:pRSAN5OYTMGtqAKToRvejw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
