apiVersion: v1
kind: Secret
metadata:
    name: secret-env
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:HKLODuWiH3yv3n6lMVUlaUJuo/A=,iv:Jwd7+LEl5t86XJ/r4MbvBE1TuWmXrN8cS4IWkfvGZSY=,tag:/d8Wvku4heE9jdAzji92aQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:Oedz12jZoCMkNuXOdnb/9Ls4vxMRS/ZvwjgYDuvM+6oxWPk6yrbzRg==,iv:vuGRKeE/Piw12RcBgNf/YFcjIbWyOu/xO5ElP5eXOuM=,tag:PEWzImnSB3vo9KnO8L6jZQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:6oYrLkyP1p971Gbgq1ZxSmOFgKNqwHTGhSEQ5/jbEUyNDjcdsh7u5tSZdgYzBOz6At5JlRwKmfoCb/ShSeCHhvnsam3u,iv:aSGsZe1+lXsYpwiF6v2xSEVX1hRPt5ok+vX7gRt7t3E=,tag:Hj8TaXq0tUUdPk7TWWWGCA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:yk08dUnW8cJtOMRoB/gSujV0YFDFm7g98VCqFBlZ3Iw=,iv:nF92nCLqmoBq5y3PCs9ToFdm/AwLZGZbDu/kYsW/IX0=,tag:Uw9L4mpYKDj+YD/zEDYKNA==,type:str]
    NEXTCLOUD_PASSWORDSALT: ENC[AES256_GCM,data:dLuXaFQH4C2PnUxR82KB7SVbGTohk5Fdrjn12H5H,iv:9fSzs1PXDj1kicql0sSdJ/reb+zDxqEAy6ssKNoNSW4=,tag:ttN0IJQ5s3Nssmpg3jHnOg==,type:str]
    NEXTCLOUD_SECRET: ENC[AES256_GCM,data:Hx93lEU8mp+ynjzHxGfWQvrtZT3pf11klC21EyOhzjtEyGnQbiQwpZxj5MzNnPnR,iv:NLzRpWoaU1p4edAQK/+cAwvF8/XV/sHx7BPKJ8o/u9k=,tag:jITIPVg1TpIZdnAPQOi/7g==,type:str]
    NEXTCLOUD_INSTANCEID: ENC[AES256_GCM,data:yoyJlrmar5NFq+CR,iv:ELla7i0FGvbTm5741KoRfrAdyNEpOn1tFpaCHipQUTo=,tag:TSGFnjeWcZXm4PDcvj73/A==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZERPdGpTNVJwQUd4Y3RX
            ZDRFNXhDQ0wxMVZiWEE1UGQwV0xEb3NBc1hZCjU2dnM1UDFvT0V3SFJ6VVdnV2FX
            ekhmZm54eXV0d3NKMklqSUZBN21IeTQKLS0tIGJEUVRoS0FYZi9Ec0Q0OVhhT2Jj
            SjBzZVQ5bDZZa2ZjaHRlSEtPWkhHdW8KwYKFuj9uKLrTHkOqKffY5jJl/22+G86k
            9YqpwmHKxhKIF4vDi2dR5ZvruSxPRFCDkAhGwbXwIRefv+AkIDhPAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T16:55:26Z"
    mac: ENC[AES256_GCM,data:pncKjzvLjBYRjkBE3COW3T7rkOu9EvSUfHh8e/2Bu9na66bIi1DtT1BQJNlFX5joU18hNFSRae/wU6sDrvO2AKu1n5t7+OlCaMsoOzIhunf8KcpcXRbPah1+ow4js+ADvsDkyTEwD07ZOFAakojDHOH1AnkB9OU2eJ1n7G8mnUs=,iv:CjmhebrTC1bBYXCjb9ilv2l1VELz0pxERLhtWjdjkWU=,tag:W3Ndhhk4X9CVL4PeNjmO0A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
