apiVersion: v1
kind: Secret
metadata:
    name: valkey
stringData:
    default: ENC[AES256_GCM,data:Un+Y6VfpX8Rx/Osch/Py7RsyYNOIMgM1,iv:ku/2o/DDC5dQTen1nH1+JZLPnfGTjoiYIhxmKjZLF9w=,tag:fP9FYJ1IX3QrDU8I33Ctqg==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MUFEY0Q3YlJERjBrOTYw
            d2ljZGZ2WXkvOWhqSFhwTjZkNEFLY2FqVTM4CkxsMEFkMjZBZVJrQVVlSWUwS3RF
            RzVMUCtTSnhvTjIwcnJ3WXNDYTV1WW8KLS0tIEl6NjNYejVRekQzTU8yRmRCVk1G
            bGNIdkljNXdnaUJtTFI3eW5Eb0lJelkKiIvLdhI4RTOXBGqCn0Ab189HWUA5O24K
            QPDfkUOnf9686N5UFiIyAJop8mGR4e/M3nQR4ARzPFMzrzYMOmU8Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T11:47:23Z"
    mac: ENC[AES256_GCM,data:wP97f6e93InnjiZhZs5f6GDY41qVq6xYNlJss1qezGVJRVQN/Voo2uctKqwrC0I4w+86K7ezNoYtiDQzSD6FpUBUAH1+UsNvJhirJe2lTZ/hDAx8fFelwJHqLhk67koldxa2rMRg+A62KSpDfHbXXKypoFqtl6JKy+wXykTJ5CM=,iv:rYzV3ydAHf5LwQv5Unx/HA7kOFjQdMZ9geEUd2s8/cc=,tag:uGBkKXSdAjZRG9Zi7jfb/g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
