apiVersion: v1
kind: Secret
metadata:
    name: portal-v2-dev-db-password
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    my-secret-key: ENC[AES256_GCM,data:Vyd3WPETYYK71N7gLp3fBg91QrTOCdUXh+qxo4yCFIw=,iv:TSLrXdBTirzgTcsETv2xsOSQNWpDfK0pB1McWDrs7ww=,tag:b4b/oi0ApSzc86SBsdJ1iA==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucGNlM3MxSnhrQlNHOElM
            UktJSnoyaTNJc29OUm4rdmlMZnNka0ZwV1UwCldNVGhKNlV3RlZRL3pKQThWK0RX
            Z2ZpUUtZRGQ2M0FpOHN4eDFtZXpHdzQKLS0tIE9kNm5jVGUvd0YyTHc2U0dicERk
            U2Q5YkxnTGNneGRtU2F5NkFkUmcwaXcKjygnpQ526XJveTBtui+NOIaqYQpPpDlK
            rY1X0dSF9EexL51BOachnRCd/gmSzhxmOcnrL0kNq5rBLlxu3xFqQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T06:45:37Z"
    mac: ENC[AES256_GCM,data:/T1Gxu0sEKR6DKPSa0y0Tyr/gNpRjw021Eu/nhSYXGBTmnQar4zPhfhd0xw7UGe+vAsO++KfguqFUSSQMUuqNO9Zbb/Snw0no1723Cpg78peRg0aci9ggPZ45d/4Hl//uzx11ruB0y3j6XR49hHmoFFamLbnzeYf7tSWCTSt6Mc=,iv:V/uCSkeVbZW13uqSLFsvFxAv9SkRDbDngQ0flabZ14M=,tag:dmhW4l102cKk4qkTZEtklQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
