apiVersion: v1
kind: Secret
metadata:
    name: portal-v2-dev-db-password
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:gODJklUpgwiMV49hqmCMm+hecO+NbES/uwvHvf6yK2w=,iv:fh0wBylZEN6Q9p9hN6E0Ql78KDcYf/ntPyQgfJeIEsM=,tag:NNj9Z7bIWVbcdGSHNSTIFg==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaFRKV1IvRFZNQjl2ZEo5
            bDBzUWFISWQ0L25zZUVDUGRqVnBjeWJJVGpjCms0RWpsSlpQUVRnOUVuakRUUS9u
            aHZ0b2pRMkZ4RHRZVXdUcmhLN1BnUXcKLS0tIG5NVW5KYXlqV1RvZTU1SmhzTmJE
            Yzd4am82UmhyRXhxQnBibEtzM012Q2MKfAy06+bm8FfsmHTHCs+Jim762qT89l5J
            jmUFSDdKNVyOPr0NyHwm5TfmS8RdgScAzi62DuPuY5j8XQbfeKTeXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T09:19:23Z"
    mac: ENC[AES256_GCM,data:/gstNyiffEB4CWtWOVRrPLtjI0su5BoNvdoVZ9dEsMiKj8NDEfkk1C/AzZFI8fnnLqAHLT8fvTpm2jhCHnThZO1dmkFxGo8gSO5R3pvR8AJ/GKnDJqRkXxCSELMj7NYaZx4tdA3ebQtads4yXafBkCL5IktHXaNa+H9BKyG9KQo=,iv:KqiGQW/1hK8RuEZBSVCDlngfoeyhD1tk1ISNqeqPYvo=,tag:9x+B+7P6BMoNUWBntfejWA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
