apiVersion: v1
kind: Secret
metadata:
    name: portal-v2-dev-ec-pub
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    my-secret-key: ENC[AES256_GCM,data:ZjuOCuSf92bRzqsxlBpZDrG7GLsPlNWzgXC/sNs15dfJnVehTCnZF+JWRlJo6QtUzGZO0+HwHgriqAqcC76s+nrjFd+LN2VrEtPSUYeIVS0UKhE9WBWfRR7kJVYR5L5Nh7mrCIL4U2m9kpo84eWb/fmzWyYWoQJWnbCI4DLTS3JbGHyxC3ma85/M2DYJDhVW8c56dpITDfUx5zDThW1uhos3aAqQYDLGFLzWc8nNFMNmVw==,iv:y3h0R+eyfk5Lprcbh/53Bq7qB4dBb3i3hmx1NSIXvNg=,tag:hI25zjR7NQYtdpiLc7Mlhw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MHpUTFpqZnVhQmQ5S2hs
            QlhmYk5TREF2U1JvVGY0VkR0eXgzZWJtdmg4ClNkYTAxNDBHWkZzcmFtcktzNzBm
            a2JXdGltcFdnSE5wN0xNUER5VWVLVlkKLS0tIDZTRUI1QjU1ZVdHZ1YwU1ZJdnI0
            dHlJRkZra1RiV2NKOTVaMVZHR3pjQkUKaEoSAqKY+RQ/EAS3hPL35H2WFQwaSVRW
            XDX/9TDUtyAec07mZoZ3/LW88kHUdMBvBw6/z3ewHroc4eG/SCDmBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T06:45:47Z"
    mac: ENC[AES256_GCM,data:tzHJHjYBHt7oV/d1mL1o6LoSe3hkPp+ZlRzKz/6q4qaEkPBVUo1fT80uhFm2DwhGrnfiAUCz2Vi7T2ThJ1uxP6IGcm2e0crhHbM/zVvZibn44a6N1mEvg2eZKqpAwN20dI1Ccru7BUptatNi2j4jzx7lwkow6gqBaMoosz5qChg=,iv:AqYtwGvU13bM1f8b2FTAPQavxfq+cfV3Y7HvOu6cXuI=,tag:K/IvJWvrnWV/UHXbkBJfPA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
