apiVersion: v1
kind: Secret
metadata:
    name: portal-v2-dev-ec-pub
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    ec_pub.pem: ENC[AES256_GCM,data:uTDjEuSbzeHZ4ZhJqu1FUmROpsfHXWYNfkrwLiUO+Jroz9G3Nl/tsCE/Hmxv4DV1sqqwEqg0lB0du72ej3fAAI2Zrtjhe7n/WJFeLO+GqN9CkkSZLK3zhCaYTJKouTvd9EtBfFI9iE9gmqTECndUAld9jqvLCWl6wcW+DeARTWUVSV9/PI6Imj85OtlCNPCIbdv8d+uo9IKB15O+O5R4LFYgGv4z6j+Qk1RshE36eBacSA==,iv:3XouImCZvycrOl+bGJq7cciQ6vJmW8iSvH5IFX7LaXw=,tag:C3B0oTMG0ZM+w4ZIG4ZG5w==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbXI3ZktrMVBGQlRJazFE
            OHFZajgzT2RGRFBqaXljT2NOZ3dCMWVvUmg0Cng1OWZIYXhReko4b1BrQmV5Zjdu
            SUVLVG93T0V1N0lpQk1qSklEV3FHNEkKLS0tIFI1THJDUjk0YzlDMm1xRVhlNGZL
            aXJjeGw4ZWNyZUhseElBSm1NWFgxaFkKb5luOPvfogvsyY1fPKg5xgHAZQI+Xke8
            QmWxDlw9kLLjNjOEEflFrLJrMab6GPB9Rcx8xAKS0oBAgGXWVX1qfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T09:19:42Z"
    mac: ENC[AES256_GCM,data:mdTvfXIHRuS6bGulBggcctr9PYSd/yyqZG71K4JVhsbEa0RAISBN0j7pGl7nxcLT68sJZt6b9AcrdExV5FWk7XNXaw8ZsplGqsi/zAKlwkqWMwUZBDY1apAP+aBm9tSMxXCrFC5hHifBDx2zm5sRVYHvrYHLOtkhcAA1exUIexQ=,iv:kJXPohh3qXoQnwz10A6MEo1Squz7ZEBXEPUqH+Urels=,tag:oGoOjyayGpHmJsGCvCua8A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
