apiVersion: v1
kind: Secret
metadata:
    name: portal-v2-dev-ec
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    my-secret-key: ENC[AES256_GCM,data:bPe1hJVS1tCh+LAWSX933O8r1reCS6C0NvaFDLtTAemuLV1nFoyD3G+H9wPWPCSdVAp0cZLKQduMgvDrKlA+GjbJuKSRrKPW3DaeX+A6rwqqwId2eHkIbjRN/O2qkVG2f4uRmp0joELdNDXK086f9QylaZ5hb5eKYM+UZpQawvS/JDElXUkGfrAfiWetqRHmoPzfib1fq1QHn4jiFNZ5r2AswLs/LnO0vLlfshN+MY4OSmPF4tAdAQiTQkGrl91ET8Q84nl+HgR4qUnNkpxukxXH55fxCc5AAI7RJS9n+UYIhX4=,iv:+mn4bjgczCkq1OHdF9eZAQ0ZRgrkND5rb3pwUoxwXZ4=,tag:zg6EPCjhb5niTGpBZWDtoA==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUmFCNFROQWY5VXE2OGw3
            dHZMUDQxY0RYM3ZoMFZ1NFlQbjI5WEpKeERRCjBBaE92eCtoRXUxN3FOL0JIekFM
            alJ0Mk0wVWEyQktGN1dnMmpaU25DTU0KLS0tIDRXQWkrU3NXbjI2dkg2akQvZFRy
            VkhGYndCOXUrVm9EaDVBYTBaSTYrekUKoHna/TOuTOksAIfv8ckGSaHbHPjLGYfN
            hcDngKiYHzo7cqrPP7UKBcxiION56RJfeUxG611AaS3I/vJ8UJPMEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T06:45:44Z"
    mac: ENC[AES256_GCM,data:tCHMEft8hsdzh4GcJt70UXfzmeKA8f20285SvTGQ3pWuej5R8A0dbl9TRSvnPDoqOcsxpGKbrKzrokTw3eqbTme7RGBrVdpPs0DfVToCHFcAxlc8nMaOmrEHpyeuvomR33Ou8ACZIYPQKYH0iq2d9BoNaFnXs9jZVzGU7sV2tD4=,iv:MQm9jR6cfDrYAInUeBYZPYCpJp1AYMqHbJ0CqKDjXpY=,tag:g22qOLt7CTkGIxuIPkYOGQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
