apiVersion: v1
kind: Secret
metadata:
    name: portal-v2-dev-ec
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    ec.pem: ENC[AES256_GCM,data:zzkbO7J5pRs8R15hqWp5orMG5kmGehG0SPOcyIKcZKIWSSeaZJ0Vj6vrIwKgGda6CdwSuNCcU7ga2QlHHClkUB9Vvdloqz4CN3gq4zfVIZ/4v3f3hqEX1ObbKYQT4TnDZlhD4fkh2RU4wmrQmY4GBs8S/DU2rvNTyy5A0b5wiSWEbO6/umvmqo5ZdJoGseLEMt9T24GBunJ17Cy6+xHr/nIOkU4YqdsBaAprJY3NhHnq/V4u1cy2wZbtHl51NKAOb+x38HKBleyhnU/UWnew4TUS9YmJW7IGjnlEdGn6+DuiZjI=,iv:/TaA+cVEd/Cd46CPQa1/sJoCcZgGl3djoVB5QUbAryw=,tag:/inItqBLixQWiUV3qxaRQw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRnhaczVOa09wamlOY29x
            dWtUWVdNa2RBNUw3WXBoa0p3bG5yZFB6aG1BCkRmekk3K2NpWExuaXZ3V0picWEy
            dHBoWC83NUQxR290M1pOekY5Z2kxWDQKLS0tIEFxMGNSYWM4WFN2ZlRQeE55SUVZ
            NEt0R3phQXZQSFI4alBVQ29nc1hSQ0UKsQEtKolBSTDHm3s5eGIJVDQJojQb10Wc
            D0xaMovreIfhi3XGmTKJF6F0X20Ha19HXizcRBBWLQTOWcsBHWunmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T09:19:32Z"
    mac: ENC[AES256_GCM,data:q6q9DUfSO5M0b3WOzi4roVDybHx+rzYRIX3uyHsDfjZXTYyWBngpvFq+C7J4OVIQqSZjifWdEcP7xNO+ag1mjJkCYzxZtPyJbMQwn8whHVm9/NaZy2MDwUCuEQDMZyWqBYjsttdqPBakb9ahTo+ZKPPTm5Zyr9lz0/KKGbETo88=,iv:aUl5SXJD41k2HTUeF+Smd3Ztq9Xvn0fIqA4mKXK8ITM=,tag:f/pCK78CkzDf53bQu5bHTA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
