apiVersion: apps/v1
kind: Deployment
metadata:
  name: jomon-dev-frontend
  labels:
    app.kubernetes.io/name: jomon-dev-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jomon-dev-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jomon-dev-frontend
    spec:
      containers:
        - name: jomon-dev-frontend
          image: ghcr.io/traptitech/jomon-ui:main@sha256:5c564dadd0242855831c462dfae1a0d22255adb264d0d43c917e9de4a1f8914c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
