apiVersion: apps/v1
kind: Deployment
metadata:
  name: jomon-dev-frontend
  labels:
    app.kubernetes.io/name: jomon-dev-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jomon-dev-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jomon-dev-frontend
    spec:
      containers:
        - name: jomon-dev-frontend
          image: ghcr.io/traptitech/jomon-ui:main@sha256:e9e57b0f544fa5ad69afa0f52504e6a6371bddd501815ffdc99435e6e029e95a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
