apiVersion: apps/v1
kind: Deployment
metadata:
  name: jomon-dev-frontend
  labels:
    app.kubernetes.io/name: jomon-dev-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jomon-dev-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jomon-dev-frontend
    spec:
      containers:
        - name: jomon-dev-frontend
          image: ghcr.io/traptitech/jomon-ui:main@sha256:92624c0e82c150962fe047db20fa33bfa76efeec78471a2a6ffb4377bf08a7ed
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
