apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-valkey-transfer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
