apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: crowi-mongodb-backup-cron

spec:
  suspend: true # データ移行後に定期バックアップを有効化する
  schedules:
    - "0 4 * * *"
  timezone: Asia/Tokyo
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    workflowTemplateRef:
      name: crowi-mongodb-backup
    entrypoint: run
