apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      serviceAccountName: litellm
      nodeSelector:
        kubernetes.io/hostname: e505.tokyotech.org
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:v1.82.3-stable.patch.2
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          envFrom:
            - secretRef:
                name: litellm-openai-api-key
            - secretRef:
                name: litellm-anthropic-api-key
            - secretRef:
                name: postgres-config
            - secretRef:
                name: litellm-master-key
            - secretRef:
                name: litellm-fireworks-api-key
          args:
            - "--config"
            - "/app/config.yaml"
        - name: tailscale-sidecar
          image: ghcr.io/tailscale/tailscale:v1.96.5
          securityContext:
            privileged: true
          env:
            - name: TS_USERSPACE
              value: "false"
            - name: TS_KUBE_SECRET
              value: "litellm-tailscale"
            - name: TS_EXTRA_ARGS
              value: "--login-server=https://room-vpn.trap.jp --accept-routes"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: room-vpn-credential
                  key: TS_AUTHKEY
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
