resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress-route.yaml
  - ./certificate.yaml
  - ./serviceaccount.yaml
  - ./tailscale-role.yaml
  - ./tailscale-rolebinding.yaml

configMapGenerator:
  - name: litellm-config-file
    files:
      - ./config/config.yaml

generators:
  - ksops.yaml
