apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portal-v2-dev-backend
  name: portal-v2-dev-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-v2-dev-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: portal-v2-dev-backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: "eee101.tokyotech.org"
      containers:
        - env:
            - name: DB_DATABASE
              value: service_portal-v2_dev
            - name: DB_HOST
              value: tailscale.kmbk.tokyotech.org
            - name: DB_PORT
              value: "33060"
            - name: DB_USER
              value: service_portal_dev
            - name: WITHOUT_MAIL
              value: "true"
            - name: WITHOUT_TRAQ
              value: "true"
          envFrom:
            - secretRef:
                name: portal-v2-dev-db-password
          image: ghcr.io/traptitech/portal-v2:staging@sha256:a0d61996b98c1a5e85016e9b442fd951e946628690e9e43a165e055752cf19c0
          name: portal-v2-dev
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          volumeMounts:
            - mountPath: /app/ec_pub.pem
              name: ec-pub
              readOnly: true
              subPath: ec_pub.pem
            - mountPath: /app/ec.pem
              name: ec-private
              readOnly: true
              subPath: ec.pem
      restartPolicy: Always
      volumes:
        - name: ec-pub
          secret:
            secretName: portal-v2-dev-ec-pub
        - name: ec-private
          secret:
            secretName: portal-v2-dev-ec
