apiVersion: apps/v1
kind: Deployment
metadata:
  name: anke-to-client
  labels:
    app: anke-to-client

spec:
  selector:
    matchLabels:
      app: anke-to-client
  template:
    metadata:
      labels:
        app: anke-to-client
    spec:
      nodeSelector:
        kubernetes.io/hostname: eee101.tokyotech.org

      containers:
        - name: anke-to-client
          image: ghcr.io/traptitech/anke-to-ui:main@sha256:c9dbb678d83a2a77d93c0ec7d1724d8803ce8233b99c232cec2c23b7dd0a9cc4
          ports:
            - name: http
              containerPort: 80
