apiVersion: apps/v1
kind: Deployment
metadata:
  name: anke-to-client
  labels:
    app: anke-to-client

spec:
  selector:
    matchLabels:
      app: anke-to-client
  template:
    metadata:
      labels:
        app: anke-to-client
    spec:
      nodeSelector:
        kubernetes.io/hostname: eee101.tokyotech.org

      containers:
        - name: anke-to-client
          image: ghcr.io/traptitech/anke-to-ui:main@sha256:e8bc1e2edfbc1bb8bf95980a8d25d539f2d2971f7f66b573c567159339631e96
          ports:
            - name: http
              containerPort: 80
