apiVersion: apps/v1
kind: Deployment
metadata:
  name: anke-to-server
  labels:
    app: anke-to-server

spec:
  selector:
    matchLabels:
      app: anke-to-server
  template:
    metadata:
      labels:
        app: anke-to-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: eee101.tokyotech.org

      containers:
        - name: anke-to-server
          image: ghcr.io/traptitech/anke-to:main@sha256:f694d000b9b008105beee265ef016c3dd8f7ba555d910b656e729d41c5736dee
          env:
            - name: ENV
              value: "staging"
            - name: MARIADB_USERNAME
              value: "service_anke_to_dev"
            - name: MARIADB_HOSTNAME
              value: "tailscale.kmbk.tokyotech.org"
            - name: MARIADB_DATABASE
              value: "service_anke_to_dev"
            - name: MARIADB_PORT
              value: "33060"
            - name: PORT
              value: ":3000"
            - name: TZ
              value: "Asia/Tokyo"
          envFrom:
            - secretRef:
                name: anke-to-secrets
          ports:
            - name: http
              containerPort: 3000
