helmCharts:
  - repo: oci://registry.toki317.dev/pub/charts # TODO: replace to ghcr.io/traptitech/charts after publication
    name: neoshowcase
    version: "1.9.1"
    includeCRDs: true
    namespace: ns-dev-system
    releaseName: ns
    valuesFile: values.yaml

resources:
  - db
  - app-namespace.yaml
  - certificate.yaml

generators:
  - ksops.yaml
