helmCharts:
  - repo: oci://ghcr.io/traptitech/charts
    name: neoshowcase
    version: "1.9.3"
    includeCRDs: true
    namespace: ns-dev-system
    releaseName: ns
    valuesFile: values.yaml

resources:
  - app-namespace.yaml
  - certificate.yaml

patches:
  - path: db/adminer-certificate-patch.yaml
  - path: db/adminer-deployment-patch.yaml
  - path: db/adminer-ingress-route-patch.yaml
  - path: db/mariadb-stateful-set-patch.yaml
  - path: db/mongo-stateful-set-patch.yaml
  - path: app-namespace-patch.yaml

generators:
  - ksops.yaml
