apiVersion: v1
kind: Secret
metadata:
  name: codimd-secret
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
    kustomize.config.k8s.io/behavior: replace
stringData:
  CMD_SESSION_SECRET: "{{ codimd.session_secret }}"
  CMD_DB_URL: "hogehoge"

  config.json: |
    {
      "production": {
        "domain": "md.trap.jp",
        "port": "3000",
        "db": {
          "dialect": "mysql"
        },
        "protocolUseSSL": true,
        "email": false,
        "useCDN": false,
        "allowPDFExport": false,
        "defaultPermission": "limited",
        "imageUploadType": "swift",
        "swift": {
          "username": "username",
          "password": "apiKey",
          "authUrl": "authUrl",
          "region": "region",
          "tenantId": "tenantId",
          "container": "container"
        },
        "trap": {
          "cookieName": "cookie_name",
          "pubkey": "secret",
          "invalidateTokens": []
        }
      }
    }
