apiVersion: v1
kind: Secret
metadata:
    name: traq-discord-webhook
    annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/sync-wave: "-2"
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:p/7fIZ5DTX7qtMo3PAbMNSaMVRXd7BkpHZkOtkXR/Ts=,iv:whiYVVf0H5TFIVKdOCnBJtIVeODv+Rq8NFDTLZuXHg8=,tag:RXNbV82k08oUJglNlghRPQ==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSUVYemNXaGl5YXlNWUFH
            UUlFcEYveml1bHBYNWJ5aUIyOFZUbWFDNW0wCkVvbE80dFM3MFpXZytGL1RIT0or
            Nlp4TXVaUHJMV0pLaU03WGkxaWdOWWsKLS0tIHVUajNxSTRyVHFWVXk1OHhwMjNW
            VEw1RkIrb05WbFBBVk1IUmx3K1RSTlkKSgNPp6FoEAwXuE83B3TVivOfpOxUweQW
            N1EA2Pt6hrkdMpnbAOLiSROhO2Sg8y4aFWpnn7mjefMyt0lSpZWgeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T12:16:24Z"
    mac: ENC[AES256_GCM,data:WvrBs1c3Pb9Nr5wJd5taS0pmBG4TMZHDrLwl2ongYs62VP7Nr8je4Q0PhsAonQXtLFpjESn+GnaCV2yFiOcdFYYzs1M49D6vYGlc0xIdf+q76ZKiy167yKZkTxy6vIZavP1a5addgMuHdYatnUqRVFqi2erEk5i8eEOriBIPn3A=,iv:7bhl07OpwVonF/ksRrnHrzCs8jGip0NDEb2lApwWZOw=,tag:BrUhZ4dVfa4iTsTvg5iK2g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
