apiVersion: v1
kind: Pod
metadata:
  name: db-migrator
  labels:
    app: db-migrator
spec:
  nodeSelector:
    kubernetes.io/hostname: las211.tokyotech.org
  restartPolicy: Never
  volumes:
    - name: grafana-storage
      persistentVolumeClaim:
        claimName: grafana-data
  containers:
    - name: db-migrator
      image: ubuntu:24.04
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: grafana-storage
          mountPath: /data
