apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce