apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    db-password: ENC[AES256_GCM,data:+QfVxcrt6Do0/5qI0kZ5AI4AU7tyBDNol3u7vvgC1JI=,iv:cxX+tpbB+l1J4dtn6PrpoozfXwBuej9RuzJ/gso/pwE=,tag:a6I6+oS20v1rKWrkouMXmw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQlBsdTk3OUYydi80VHRJ
            WXVZQmRTTitrbUo4WEFjVzJSaFJkN0pER1N3CmUwakhHRHFHUExjamd5K3RjSEp6
            THBUYm52eVhndlRGbVRtS2tvNnR1VGsKLS0tIGZkYldnRTJ6eDRtbHdZMDhiN285
            VGpkSklaTlRlR25sczlrZi84dEtKazQKnm7w/XQn7kcQTfwpFpEhPfRp3CNcK2I2
            RnR6wxNkSrh5fqfzozgRtJN4g/aGig/98+j+tlTIKVAyh4lTpHHtfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T03:22:52Z"
    mac: ENC[AES256_GCM,data:pv7orjGgEVtWir+6X0e+AjhFnyqaRVud8z8PdZzdSUottZJQk/Et8JgJDg+5Nta/E1K2i+k9LHFEZ9dx+Y0TfhjB4k2aLKqZoqrgRtxMOzQ23gCSWWZmT6iSVzs0CDW/Vs0+XHu2M7OW/boVvFxkjWTRKr2sJ43PR8dHNSCxklY=,iv:nTTzhH5tN32LmZE7HDhfuerV2ZR5fPTwfpYSJ9PciYg=,tag:1vY2d3OKICtYRONY3j0GWA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
