apiVersion: v1
kind: Secret
metadata:
    name: bot-gpt
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:9SlqSs0=,iv:92gqYcoA+9ZZPVg8+VMxBbKx9kCS0b0P9vaBMqoIJNI=,tag:F/KPNkbknDQJ0I80b+4AFw==,type:str]
    BOT_TOKEN: ENC[AES256_GCM,data:3tGbPL8=,iv:t19J3vhpiQLFjjXE/9ma4LjFnQTIZGwBPNDckL3Lkv0=,tag:KOeowSBRfZqtWyZ4nBRnfQ==,type:str]
    STAGING_CHANNEL_ID: ENC[AES256_GCM,data:nE6d6CM=,iv:GJjeDGw3uKtJDASfAzNyoSdqX4pfBTIjNwW/glo+HhE=,tag:gidFtLm3XoHvsEXPJMN/9w==,type:str]
    GRAFANA_MCP_BEARER_TOKEN: ENC[AES256_GCM,data:xaW9KPk=,iv:xNabvdFM6cO0KC07T8Du8H/w4k4/8FppSHsE9gixo40=,tag:RcHGjl9dbRB9FyiuVSvnTw==,type:str]
    MILVUS_API_KEY: ENC[AES256_GCM,data:cbm4B9U=,iv:2ASB8XFr95Cn7vo+w9eftUBYjwlUyGh628qQEUnupFo=,tag:HK1JxB3d0AwUMOEf7hxsZw==,type:str]
    MILVUS_API_URL: ENC[AES256_GCM,data:x4u/74Y=,iv:Cga1p/C1wsanTVkCxfR8cq0mIM8+Y2QuqxBb8lfgouI=,tag:AMxr3+U4pPmfaUD08zgPPQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:EDbvwco=,iv:RPUn9YA1/NtpXFZa3z8VBkB1hzlgcbMD3koOd9xkD2k=,tag:fPJXVAexEWk6z2Cu2L0cJw==,type:str]
    OPENAI_PROXY_API_KEY: ENC[AES256_GCM,data:zu37q24=,iv:7SsRAvD5MmDUPaEhcyUZqe2r4Gx2G+ZZT9KXYNG8dy0=,tag:C4w7BgjPpD4sQAns+AahYw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZXYxbzhreWg2clV5M2hF
            ZXlOTTZHZ2hLOG1lMk10QkdNQzliczBzNFV3Ci9nbW4rUEwrMk8rUTFsVDduS0sw
            T01RMVBNZjRTYXplaGhDREJPLzVTdjgKLS0tIDgra3ZLMW1xRXhRUWJVV1RNeG1v
            WEVqSmVtYTZ5eGlLV1dqWk9YSXlMTDgKYGsIzCvVSgJHu0p/2PVt8au+OjRW0mjC
            Jr7soC3NsBI58MQRh0hhf7EP/TNttppcpVR+otHhPvMke5fJs1Z4yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T15:49:10Z"
    mac: ENC[AES256_GCM,data:S+HIgkQFxm+jpuZU6cTmhIhOVOCMtkjAoHLH3K39Z9NPS0mRC9KIbqLZss/fEay8l6SF6fgkcG+AUOY7BkpAEITW7N0CwpPOQ7Cojo2czV1ON0/xigEm0Paw2lLcWNXSdkxZZYJEyrdWfNEgbcL+RwT2B9jOn4kDBUBvtg/G0IE=,iv:tp02uAT0BVBWrh0xOrY9+YC3e20FgX9ct7bZ/WTsJHw=,tag:zi5SGTMJ9RUseeNpwtOBGw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
