apiVersion: v1
kind: Secret
metadata:
    name: bot-gpt
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:3+LxLp2MczNW6deD4BCvvFnvsx1Spsu0AO3+PF9lkIg=,iv:+guZwXqQ1M9RWwXkA6bWWIKSCrsEku93zTiGrRn9K/4=,tag:PB7fRMQKkJvhktGd8z1qnQ==,type:str]
    BOT_TOKEN: ENC[AES256_GCM,data:lVllKs39Umu15VIm1zotGpV4qmpHNfz+LPEsOHJXy9a+4PX2,iv:ojXf0iw8M3mUzSR0y/Pew/EObGmqD0elTopWFEiIFAc=,tag:DeH6auQnn712mdHRFOaF2Q==,type:str]
    STAGING_CHANNEL_ID: ENC[AES256_GCM,data:qsBMUJOeqOFu5FvrpN346ZXWdeWLdZyXzFMsnK3kw1C2J+oe,iv:u46BAS1DpDgtDnTEMwih1D20sKZj6MnUoKTRDaYvjXA=,tag:NkxTSUFhWPcQWPwWmrXNgw==,type:str]
    GRAFANA_MCP_BEARER_TOKEN: ENC[AES256_GCM,data:3aiY9/8rdUTFROM26BPaY/FE/bByL2YsA3KhwWc1983TtSxpNwqDIOTKprt2UVWmRSDTrI6eS0I=,iv:y0Gck48kKN4lqGAeIkOSwBW4TXxHRagPmLjZsF0oABg=,tag:o8mcoQ23edyQpZ2YLf1s3w==,type:str]
    MILVUS_API_KEY: ENC[AES256_GCM,data:az7rUeUSzNnNYuCoccShn4m0WN2IzPNFYw2ja11yOOgc1ukw35qtXoybVNgOkEBP+oLkIL5Iia6QPHxk04LEbRteCNBZZ08GdR3BI68A5aPMplq8p5QExSspmviHVnaeVxg80ova6/0=,iv:84Ae8iv8cva/8sK8DwdjrT6NfZ3MqxT7Cg0IhmgtZsc=,tag:SPuBN5Nuq4aXqbiTYHDuiQ==,type:str]
    MILVUS_API_URL: ENC[AES256_GCM,data:MWNyzkkTIi6nUkVM/TBhG6muQ9ULqClaJGoHikjhnCYhN1NeRvMu8AyNdsjHNVLUQm/U9RP6H1vc1GW5+REjY68i/hrj,iv:5ja9V5nf+epNgFdDh1Wso5E/cA1vMW1h8VQKgmuaED0=,tag:y+lVTsqAkijQ4ZhKjZCbIg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:whpq8itwU0+hHWwQzOjybtHsihxmvWHZlHdfQssmwG1hCeKVK2zvYwMxJpVafoj3q1XDheQJOro=,iv:cncdECnRydeMPEd7vMhqR8qFqk1o34S41uXFOTXXFHU=,tag:HwerjRnBYahKFrGRsjtZYg==,type:str]
    OPENAI_PROXY_API_KEY: ENC[AES256_GCM,data:aCZuMO4lWXXJbetzPVvWUi1XTmpz07j1og==,iv:w/SE1LWAKQuUW02nOGiqj0uQwMKC1/b42xdLqYH9OQY=,tag:+gcedyaj3fzkZGupnjFj0g==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoK3V1bUtJMWlOMmR4eklv
            L3g1emFTWlBEemxiRXZYMGVSVDJHZWRtYm5RCjc5QVVTNTRwOU8zYkhaNUFTRk1Z
            Q0RzaWhsR3VEdUtFVXM0VEtkNWlYNXcKLS0tIFVLODNnSU83QmwreXpUTmMxZldQ
            eWZqb1N0QS9iZ25menVjUlppYmU5M28KPZQV9QHUzepOcKbAL/C0xAg15GUNmGfM
            NpaDf/Ldqf5XkUr8dq0OWfOiHHOdlDmJ97t5AAxTfSPZ/9Hr0D8b1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T10:14:57Z"
    mac: ENC[AES256_GCM,data:wY84BJwdRwVjxDVycWxWxptBWt9ERRB5LvxrKLfrNgRe1S29uCf5VHzxZUTASXbX5+akK+mKvDfrfdh2BTlYQGbSJJEjzV6qOg0N0MCPdUPq6eV5RqmzWXz5vcUmiR5nzqgdxclI4Ef4MRaVdRrowvmznnQCu6CNxmZieHBt5y0=,iv:3Gre8WD72gVnuiCR2gZQ7HymhnYJYBIsbKZ4PB3JuW0=,tag:xYw023skxmv100YjaQaehA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
