apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  base.config.php: |
    <?php
    $CONFIG = array (
      'passwordsalt' => getenv('NEXTCLOUD_PASSWORDSALT'),
      'secret' => getenv('NEXTCLOUD_SECRET'),
      'instanceid' => getenv('NEXTCLOUD_INSTANCEID'),
      'overwrite.cli.url' => 'https://drive.trap.jp',
      'upgrade.disable-web' => true,
      'trusted_domains' => ['drive.trap.jp'],
      'apps_paths' => array (
        0 => array (
          'path' => '/var/www/html/apps',
          'url' => '/apps',
          'writable' => false,
        ),
        1 => array (
          'path' => '/var/www/html/custom_apps',
          'url' => '/custom_apps',
          'writable' => true,
        ),
      ),

      'mail_smtpmode' => 'smtp',
      'mail_smtphost' => 'smtp.sendgrid.host',
      'mail_smtpport' => '465',
      'mail_smtpsecure' => 'ssl',
      'mail_smtpauth' => true,
      'mail_smtpauthtype' => 'LOGIN',
      'mail_smtpname' => 'apikey',
      'mail_smtppassword' => getenv('SMTP_PASSWORD'),
      'mail_from_address' => 'drive.system',
      'mail_domain' => 'trap.jp',

      'memcache.local' => '\OC\Memcache\APCu',
      'memcache.distributed' => '\OC\Memcache\Redis',
      'memcache.locking' => '\OC\Memcache\Redis',
      'redis' => array(
        'host' => 'valkey',
        'user' => 'default',
        'password' => getenv('VALKEY_PASSWORD'),
      ),

      'objectstore' => array(
        'class' => '\OC\Files\ObjectStore\S3',
        'arguments' => array(
          'bucket' => 'trap-nextcloud',
          'region' => 'ap-northeast-1',
          'hostname' => 's3.ap-northeast-1.wasabisys.com',
          'use_ssl' => true,
          'key' => getenv('S3_ACCESS_KEY'),
          'secret' => getenv('S3_SECRET_KEY'),
          'objectPrefix' => 'urn:oid:',
          'autocreate' => false,
          'use_path_style' => true,
        ),
      ),

      'dbtype' => 'mysql',
      'dbhost' => 'tailscale.kmbk.tokyotech.org',
      'dbuser' => 'service_drive',
      'dbpassword' => getenv('DB_PASSWORD'),
      'dbname' => 'service_drive',
      'dbtableprefix' => 'oc_',
      'mysql.utf8mb4' => true,
    );
