apiVersion: v1
kind: Secret
metadata:
    name: tempo-s3-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    s3-access-key: ENC[AES256_GCM,data:g2ovJWCjziRpuNrxZzdT7Fu3EZA=,iv:H0JcWSNHAj/45ybY61l6Ikr1pGuD4i0CmW043sR2lUE=,tag:w4dvqYWAemWYEqjRMM3RXA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:wIQWDq8mcnYkXK94B/19uFxYv1nIJQxj2gdwOdi5c9frcYbVPfBhIg==,iv:cNBrjozrhcyYueiSVWnq3hF4ib48kvC1AihFNzrInIQ=,tag:h12tHHZFz37jx4AAwMFihw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ2NHRXNBOXVGcDNUYTM2
            UTRmYVpIMnE1WWVCL1ZaNzBaaGJkOER3bUVvCkx6TlBjQU80dWxyZ2I0L2tzL3lE
            bnIzdk9QZ09Bd04vQ2VJeXhycTBWZVkKLS0tIGVkblQyYkF4K1FrYlVpQktmMWwy
            WEs5amFiZnVtQ1hiOUFVY291TW5mejgKkhTLrheYnrW7Wx4hEF6BDAehMZhdJ0Lu
            c0mrscTPQ3iDX8v8J8vzXIW/Mwqi34/8sYdKZvJQuUwY0guVfMpiTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T12:48:49Z"
    mac: ENC[AES256_GCM,data:CKBZfdb0WSDAoFO3iBx65jihgrGhZpmrMpf0JQPm1gHVv1R5qYXkp3br/AOUfLIzGUBXPCDMmUYNv6wnAm2iU+nGiSR84bR9ZT2uLEtP4MoFv7T65KaYEUEtj+1g1vtLx75cbZBAOYSzvbn2cbZWiTIOyO/4FzWbvw2UQ4V5vKo=,iv:h67fT8X/W/djWRLsNKZxOB8eOc86CVtivGqKalO3hj4=,tag:/rt+5g+qNBCifoIlnKtyAA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
