apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-frontend
  name: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: eee101.tokyotech.org
      containers:
        - image: ghcr.io/traptitech/traportfolio-ui:main@sha256:1aae3aacd6acdf18b5c810f997b257066a5018a089c85d113087e5572836bf8d
          name: portfolio-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
