apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoria-metrics

spec:
  replicas: 1
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: storage-longhorn
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - sce312.tokyotech.org
              weight: 1
      tolerations:
        - key: monitor-node
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: victoria-metrics
          volumeMounts:
            - name: storage-longhorn
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "800Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
