apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-longhorn-storage-tmp
storageClassName: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
