apiVersion: v1
kind: Secret
metadata:
    name: crowi-auth
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    CROWI_INVALIDATE_TOKENS: ENC[AES256_GCM,data:umJax+aRUK4F35ZkWRICw2CpB8FQeuf3OwtaH5msLiWG498twZPfJ26BZWz9A3pd0tbUCBBQWw==,iv:JC94VnyNNtkrPSA8MVo2jKN7NwweJCrYgdFzgtt3NvE=,tag:M8lhMAsObMMkut6t6+NE1A==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTHQ3RmNGNDNob1VvUXdk
            ZzJ1dmtQMEhNYkVCMjBUMWpBOVJyN0FFZWcwCnJiSVFPVStUMWN4eUxjTFJUSkNh
            bGxONEdUQXJkcmd5ZTI4cXdZY2wxcTQKLS0tIGwxeVpNZ0MrVEdmRUQyNENGVUYy
            eGNiQjZvVytJWVo5V2FlYTM5eEVESWsKSqphCXLP5GQEmm4SUJPHMBWtcG+7Cn6m
            9VlL6aHajaBems7BZsFkLmOm2k0A9e1+/MTLTZwxFdQnhHj3igF+xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T13:15:44Z"
    mac: ENC[AES256_GCM,data:wRX4cbO/dvT8YSNKFLTfvO52vNtR7OCX8FIK14JpcxoDD6lmxa6pMSngmwi8epnu7rp2GSVJu9+4SqbF+yCAy/bBJ7+x/cltwsgV17TTCYiuRlZS1Lgw8pgxwxuqr6ZM3hsM1k0ocVpG0szp44iFIht+ovuVJGMnn20K/z1u36o=,iv:obe/ulYmxPZU0A/cg37NhukiGCJcr1pXGU/4lxjR7pI=,tag:g5hQu6Gmt3OjCpHpzXlIow==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
