apiVersion: v1
kind: Secret
metadata:
    name: crowi-auth
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    CROWI_INVALIDATE_TOKENS: ENC[AES256_GCM,data:oaZZhLbZSmCTIpuqPWLB7hF2ERvOUz744SqfdGw3ZB/5iiyyL50mUiYOVwtzrVLqMuUt4UEv0i1qR+9XiWuqHdX7RvpYPAOJ1Jbfjh+DinkMTOoeNNuArq60yJ6ezVMpiWZRJub8ucENTBvSqFTByNKbL/L5ueOL9QEL5+tGOQ2AjNFUyBPc4MvDj9cT+eiV74Z+ozpbOXvqwN4nY1Lq/Zg8gtdnVTvEU1xBDDX1cVojLyk/+qR6IHiDff1fu/qZSzh6Jepbvd53jeAPrghzJSeRZDgAtx888X7Y9dXXevs10/duZucotGmYInddU3Wgh7sywfSzwArutQk+yusc/lQH3AOV11TEpqxxJ5aNqPzFP2NH86txXJFc26s0CkRO5YFm/mZYDgOn4HCno9bFfmd4HuHY7SdYUl9n0Uw4GfVw8d/9BX8YOC1QsTxu5n4EUMtdf072zj9HUnVTHi9YOqRlZNjHux+4zFdpBIjTttrFKITIjU/HdNYUuk4+cfsjHasg7/OMThS44tSKyqhC6FJ9L1ximS44ogaPSVu6jxz9a5iTfpNydnWYGzs3jXOgyp+fY/QHQB38x/vAnel3sRY9PTpqUQ1uX21r3YtLjEcIPRmsZdcvUH76zgL82hRZZQ1dtH2+5Oi1hnoFlGdvyYFke+xWFXHbz7yH0P65IpDCBB1WE12Hp96iDLXIhwDzxs3qu4espgA0hhCUF/SMZiyNif60G5hrdWdfFId3qNYu0K6PNzEEKK9l9W0dl/qNJeunE2KYFnTbgGGU9dBcNL8bdM+nPmfcHi1I90DkRXxecP7qSr/plHn877hr/kFicuLusyolFw==,iv:YCp0vi3fU04sIXXfZ7oAqIhPimOmGIDqQEff66SX5OE=,tag:D5B6vpYrKcS0CIVMmHhYbw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYmN5Z2pMdnhlQncyTnBa
            SHA5SFltSExRejd4b1BaTVRuU1lQcHQ1VTE4CjhNM2RYZExDbTc3VGRoV0trQTJB
            aWZ1ZW4xeG9vUU1jVnlvaVRjcDVzeXMKLS0tIFNaaktZcXR1SzVHNFFmZE1CcnJH
            MVpZd2F0VU9MSE44OWVGdmVHRk0weFUKbewmefmW/RPLLW0B99nCHE/DksToXydj
            TfgTUGenaTQGDnYwGV9WStmCFcXFdcm3B74I+vNsjWlt97SG66tpXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T13:26:15Z"
    mac: ENC[AES256_GCM,data:hHEW65GRyfZ4XyUZrVgXMY0iCpSnR3gLThP9oJvFzvTbTfB/OY/9HZ20Dj34q5smUtnGR8VISdK/Z/08FG96V++NCANG8WRqLGCsy/0v6iyWcUY37xfUr+VaapMRZtMRNGlDi4VAcCL2czmWZRY0MGzRE5vzlfGs2cnaKnQgIhY=,iv:Z2B+XXRj00VTydcjYD70x29N4PUm5+qRAa80+98RK8k=,tag:n/DQY7tgBGdP+0pSYsjjpA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
