apiVersion: v1
kind: Secret
metadata:
    name: crowi-swift-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    CONOHA_USER: ENC[AES256_GCM,data:3DmDjm4Fgv0uyAGb,iv:6NsZak9zPauO5r44hLhK0VMYF1e3hyLXqp78uuug4uU=,tag:e4OtNJC+PXCsFK+6Dd64ww==,type:str]
    CONOHA_PASS: ENC[AES256_GCM,data:ZPlMO2l0oZkuYJWXy/ib39UwOmmrLYw6HEG7N62hTYA=,iv:hkTqFWZm7m/0rtze3hMYtuKH6/7grVFdGHKsJKECAI8=,tag:amd9KgCT18D/ok3aoSg9ig==,type:str]
    CONOHA_TENANT_ID: ENC[AES256_GCM,data:25IWwR26YvPpAaNWHeRjjuRMUYQdvfPf6+QR+hYqUhg=,iv:LlaWEX3W/5izKll1W/JnbWX6ULFoFomVTNuxMi0JjQg=,tag:SIABfMpA6I5YFFJAj5xtVw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYVhqZzJ3dTBOVno0QnNR
            eFhGczFPS3hWdlUvWm9wWWdiTjJyOGI3KzBJCk9aSEJwY3VUMlhxVnpNMWN3QktN
            YTY4Sm9CZ3QzR3I1Uy9LSGZab3RYT3MKLS0tIFJBZFdzbTVuN1BPbE1UN0FIWTRa
            RmIzMThKRUJnNXVkdXNPSGo0dW5WbnMKxr/bZ79lFY3K64bmgMe/8rSraWpul5X4
            R8lGNGsefO2fTFiuj3mArg5LKIWJhnEFIUV106RjqEAaeh7yBlSRiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T15:56:02Z"
    mac: ENC[AES256_GCM,data:z3LHyaMEBwzqsFSYLXPPR8icKodt26t0uEEg9NGnDxncK6M+xSQTL3zgEYy66fOnDiV/6C73JFQ80G4OSQ3Rq7bvi8UtBNrF4ZiK69TXso0/r+CKHse1Jef92Rf4GkcKwwxCoTeX+x9pxv2kMZ0IyWQXr0e0ns3SCa5WBu6NeMU=,iv:LHaEnist9de7hy/uErocpzhOxyjQgAbk2475vCzuKIw=,tag:oIjlFPhiAUTOYyoHlVn6Ng==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
