apiVersion: v1
kind: Secret
metadata:
    name: crowi-swift-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    CONOHA_USER: ENC[AES256_GCM,data:uDAlV6foq2c2KJku,iv:eVfYDHvo5NuGiq1/ondb8vOwjEzqTWqx+yuNju8Ti28=,tag:6sE6r08hDOtkx2lo2bVt2A==,type:str]
    CONOHA_PASS: ENC[AES256_GCM,data:k5I8sH14vGjL47OD,iv:xorED5ow8ZausD780blpQIDItEJ2s/jaibLoiVLqLIA=,tag:EbkHiItKpExNeR1uOmvL+A==,type:str]
    CONOHA_TENANT_ID: ENC[AES256_GCM,data:A1qMcNHS+WcpSQf8+9U0OwyuNyBJW8RTrHje56SHwc8=,iv:PNy0M2v0FElIw+tIsAZECJy4PlEjZxfz43YDPBTt9sA=,tag:g3XEHS6FNAtwjLQTsz+elg==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTXB2SDd1ZFB1bTN0azVE
            RkRwMVUvNm9VeEV4YnVrZG5MVzhLaFlGeUEwClJQTi9pNG9GbHUxVTd2WUVpYTdh
            eFp0bFA3Vm8vbUwydUJYUlNFTkRFd28KLS0tIE5TeXZhQzBmUW4waVB6R3BGcG00
            aWR2MTdvZGtxaDFNUWE1RXZab2hvQjgK0jkL4lVVpm5ni7qFneYlxClA4QpTJO/4
            8MJ4GJ5vIuSlbt+Ru+L5BoTg0/bod3bMnKhSn3qsM7wzn80eOQ/cpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T13:08:57Z"
    mac: ENC[AES256_GCM,data:3aIDgnKB9eQeAHS3dInsQeOpMDgZ+liY6TXy6aJblj6N0uwEzx8rS7C9RhMsgouwG5Etz6VlpH7jt5xbqXrOHtczBcoilCrDVWO/IHDCDVZSrliFvkUnttkU9nS5kmI4e90gi9JyUFvs/Hgmj+swHHrBymt5xe/D4uLS+by63QE=,iv:Jj8VZiybNgMBsSRl4K2zbf0eUPehmhGpnbsQIJ7Crp8=,tag:qp4IfRFNng51zLiVILEQCQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
