apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-deployment
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: eee101.tokyotech.org
      containers:
        - name: traq-backend
          image: ghcr.io/traptitech/traq:master@sha256:556fb8ef3a23879d9c40473fb0204532fd8bb65dbefeb3da1946216e9fdf1cf5
          resources:
            requests:
              cpu: "20m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: TRAQ_EXTERNALAUTH_TRAQ_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: traq-config-secrets
                  key: externalAuth_traQ_clientId
            - name: TRAQ_EXTERNALAUTH_TRAQ_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: traq-config-secrets
                  key: externalAuth_traQ_clientSecret
            - name: TRAQ_ES_PASSWORD
              valueFrom: null
            - name: OTEL_SERVICE_NAME
              value: traq-dev
