apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-deployment
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: eee101.tokyotech.org
      containers:
        - name: traq-backend
          image: ghcr.io/traptitech/traq:master@sha256:cab2d1f31eb050141b5f22f094e2ae9e2f431716d5eb3d7d2a28b8ca94e06114
          resources:
            requests:
              cpu: "20m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: TRAQ_EXTERNALAUTH_TRAQ_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: traq-config-secrets
                  key: externalAuth_traQ_clientId
            - name: TRAQ_EXTERNALAUTH_TRAQ_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: traq-config-secrets
                  key: externalAuth_traQ_clientSecret
            - name: TRAQ_ES_PASSWORD
              valueFrom: null
            - name: OTEL_SERVICE_NAME
              value: traq-dev
