apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-deployment
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: c1-203.tokyotech.org
      containers:
        - name: traq-backend
          image: ghcr.io/traptitech/traq:master@sha256:83fde62f6129810c2db0a024318408ea072c0e084859d4265590bc05ce041ea0
          env:
            - name: TRAQ_EXTERNALAUTH_TRAQ_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: traq-config-secrets
                  key: externalAuth_traQ_clientId
            - name: TRAQ_EXTERNALAUTH_TRAQ_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: traq-config-secrets
                  key: externalAuth_traQ_clientSecret
            - name: TRAQ_ES_PASSWORD
              valueFrom: null
            - name: OTEL_SERVICE_NAME
              value: traq-dev
