apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-frontend
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: eee101.tokyotech.org
      containers:
        - name: traq-frontend
          image: ghcr.io/traptitech/traq-ui:master@sha256:ef045e1002fcd08fbe457c1fa99059372e1c1bab55b10d46e3c8aa04d907a4b4
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "40m"
              memory: "128Mi"
          env:
            - name: NEW_RELIC_LICENSE_KEY
              value: "NRJS-5c70f08b45082feb140"
            - name: NEW_RELIC_ACCOUNT_ID
              value: "6862108"
            - name: NEW_RELIC_TRUST_KEY
              value: "6862108"
            - name: NEW_RELIC_APPLICATION_ID
              value: "1120421442"
            - name: NEW_RELIC_AGENT_ID
              value: "1120421442"
