resources:
  - ../../traq/frontend

configMapGenerator:
  - name: traq-frontend-config
    files:
      - ../../traq/frontend/config.jsonc

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: traq-frontend
  - path: ingress-route-patch.yaml
    target:
      kind: IngressRoute
      name: traq-frontend
