helmCharts:
  - repo: https://helm.goharbor.io
    name: harbor
    # renovate:general datasource=helm depName=harbor registryUrl=https://helm.goharbor.io
    version: "1.19.2"
    includeCRDs: true
    namespace: harbor
    releaseName: harbor
    valuesFile: values.yaml

resources:
  - certificate.yaml
  # Disable public access while Harbor drains its existing jobs.
  # - ingress-route.yaml
  - gc

replicas:
  - name: harbor-redis
    count: 1

generators:
  - ksops.yaml
