apiVersion: v1
kind: Secret
metadata:
    name: database-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    namespace: harbor
stringData:
    password: ENC[AES256_GCM,data:1n12B5W6JXo=,iv:6+HJUeeBuxD4iJhDz2tSBPYqmNb7P4JqaWcdJ5PY02w=,tag:ZgQm9YsczkhuL7FGtNTy7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYW9ZSGljT1NMZER6YVZB
            S1kxcS85cVJ0by9DdlFUM2dBSEorYThZNkNvCkp6UE5NZ0dtdVYxMTQvckVGK2da
            bVBzeWU0OGxzVTZVdmgxS2JMZ2w1UGcKLS0tIDc3MGZDa2N3bkp2a2RDdnBwWUFl
            eFRMTXMzUVNVUjdLQnNhY01Hc1hIV0UK54GZ06E4dNkk35IbesRCUys7jmGoML5j
            esBqi590UP2VUvJ2I0VSZgXTjFJafVX0W/xYt/+YHlUV552FLiIubw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
    lastmodified: "2026-07-15T02:48:08Z"
    mac: ENC[AES256_GCM,data:WusQMt83/d1QAytI5CWexeUdJCleUbgeTFpN8p4UrrNxBy9S9+BwKdG2N89CCdPDfB3iXcBIN5YIpI+Zm7C5EJJhhB0DPxibG+9c/fLf/N9mxNzUZa/ZaGCKtYw7Mmk0zZjIqzgdL4MSe+DynNRNsmcdB+4AGYlSiJWdp04PstM=,iv:hylRtbF1NmnXvE1DYsOShqBKbrhxBhSPAegyCdqAQvE=,tag:HuZ+NqFmaveuHRpg+I6L7g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
