apiVersion: v1
kind: Secret
metadata:
    name: internal-credentials
    namespace: harbor
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
data:
    secret: ENC[AES256_GCM,data:ODOHf+uiUn3yo8X4mcWiPdAA/jxWyxC0,iv:rmrAxbzqELF8ZjxPm9NCVm+QbvE7J62z0BwyCUB8WDI=,tag:svb/OZYXL3BYiGFfSVFVeA==,type:str]
    CSRF_KEY: ENC[AES256_GCM,data:c3wZpKTLTJtg8Kxtb6TNDZg5720mWqTFpynQ6UQfxv2j2bt0pKIwgRN1tLo=,iv:VIoo+vmCEOIA+wGwkHi5DTpWdLgKGSvIIhgjBcyVZpg=,tag:BvFh/Gi2LTgOC/Olrwmazw==,type:str]
    JOBSERVICE_SECRET: ENC[AES256_GCM,data:mL5Q1bmOm+fKLTjDjIAKfk5+v9c82I9m,iv:xLpmFx2AOvwdZbtrh33HSzWNxtBaEEysP6umU7O324w=,tag:TM0TCQMQFDpMyDOwE+TiWw==,type:str]
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:82g/F8VZ1ixJgDLGZYAFDSTaeDNDt8EQ,iv:zHryhfjzqI3jqr+zeGf6ntrMDJ6E6rgjZLgIwla/SAA=,tag:0dZmVs0acGJj/pXOHNDPAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ0ZFWnY3Z2Z2L3lDRzA5
            YWlLS3JabkpEaHh6bzdDOUdVR1UvMU94TFhVCmJnaUR2cU94V1JwZ2ZoK3o0TGx4
            YWIzaUE5ZWdqRE5GWitVTUp2alFYZm8KLS0tIHlGNmk3KzAyQjdJbHJKbm5RQ3lh
            SzFoQVl5U1lVK3NJQkNRT1FCTXg4R00K4ua65NbZGFlzrfLoQrchjHjs8s4YGpvv
            +n/AlpiXjVHmAlBGz1B8q/pxLM8dvDhgE4erEUQ6QtMWJcUDanLsHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
    lastmodified: "2026-09-06T16:42:33Z"
    mac: ENC[AES256_GCM,data:S/BVLKu8PF6uLhMO/JKpqaJdYCP4bI1eYd30P9+oOxO3hqyaPBgdSusN2Si1On/IVgNlA2TPzqjQ17bj8I24amtJdPA9Dlv7hFAf3Kd9bDVipxGVZgp+sXdiK+6mQP63Rwn1lEMp8j3Ix3Tm+o/q4KknjJfv+dZZLn16HUqjJ2c=,iv:BDXa4KmIzlCtRZ9mVOtwn1OlHlpu4klDtGMUyXpQDls=,tag:oU8NIiHLIAQ2Y7xY0W47UA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
