apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    namespace: harbor
stringData:
    REGISTRY_PASSWD: ENC[AES256_GCM,data:gEMK/o0qaMg=,iv:5bJ54yaDU1k/aMQZ9Oi6JAxoVd2SsL5Dvp6oAW8Zn8Y=,tag:XnFE5gr4SXiwwDpjc+CI1w==,type:str]
    REGISTRY_HTPASSWD: ENC[AES256_GCM,data:1WYjYimIaJd2grtp6yWLDcDM7IOZaA9CiMYbpoGkx+cEFbuXq0o0I4cqB7W2d7dMAJqpEsVxGQInBMGbey806lxW5vVi,iv:8EZI83B8VCNnnRbWYzv5mZng2ivn6orn6NKrkSvivnw=,tag:pVVJ3D270fJOcDataKlmeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK3h6UWYwWFhtYXJpanpW
            SU1qZ1NPUUtuVjlCd0RxVWVvWU1tMFpyWkdRCkQrdVNHQ2FLaXl4R1hCSjEzRW4r
            Qy9nWnc1YVlESldlcDh3d1M2c0FIV1kKLS0tIGNiVE1KaDdSRWRHYmRkQ3VDaFpM
            bXdacUFSMHptVXpkV0N0dXMvTmxJRDQKbjpCDIDZ3FwnW+Mn6I4Ij1vh8gRSNzYr
            mqv+tYWV+f/DrsHVkAFZ5AzYXVdqVHHPNGkBZE9jf9YGVGgoGEMUhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
    lastmodified: "2026-07-15T02:48:08Z"
    mac: ENC[AES256_GCM,data:eZ6Ly8xD+HAxJA42BExLsemXhQjew+5Z/LoBUbh9T2DMjxH5vbfTU2vSbN8GVcSf9r+yi8PGQ/8swnr+cwEm5GstnFxUCFblggRJJ5GF7vXfL/nTDfv4riqjXRrfggKyntTejtSowWERCaPCz2EYXN2K7GwBy2Dy82PyDGUvx5A=,iv:2zxKM2XC9BJLMpSaWh+E0+bMPLGdqZ6JIAIFY/qlsDA=,tag:8EvpnxSky0FDW095YEXXvw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
