apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops

files:
  - ./secrets/victoria-metrics-proxy-tailscale.enc.yaml
  - ./secrets/loki-proxy-tailscale.enc.yaml
