mode: dev-and-prod

repo:
  owner: traPtitech
  repo: rucQ-UI

webhook:
  name: rucq-ui-preview

tls:
  secretName: preview-rucq-ui-tls

host:
  base: rucq-ui-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/rucq-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api/`)
  service:
    kind: Service
    namespace: 'rucq{{ if eq . "dev" }}-dev{{ end }}'
    name: rucq-backend-service
    port: 8080
    scheme: http

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/rucq-ui:main@sha256:f194e6a6158f8fdc46b93f7573a5b8057370aad85cd8b4fad1a58e65454ae322"

otherParameters:
  port: 80
