mode: dev-and-prod

repo:
  owner: traPtitech
  repo: rucQ-UI

webhook:
  name: rucq-ui-preview

tls:
  secretName: preview-rucq-ui-tls

host:
  base: rucq-ui-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/rucq-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api/`)
  service:
    kind: Service
    namespace: 'rucq{{ if eq . "dev" }}-dev{{ end }}'
    name: rucq-backend-service
    port: 8080
    scheme: http

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/rucq-ui:main@sha256:5d6638ede47f171c9a8efcf306c8bbaf8ee24df656f4913907f4fe19d72128b6"

otherParameters:
  port: 80
