mode: dev-and-prod

repo:
  owner: traPtitech
  repo: rucQ-UI

webhook:
  name: rucq-ui-preview

tls:
  secretName: preview-rucq-ui-tls

host:
  base: rucq-ui-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/rucq-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api/`)
  service:
    kind: Service
    namespace: 'rucq{{ if eq . "dev" }}-dev{{ end }}'
    name: rucq-backend-service
    port: 8080
    scheme: http

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/rucq-ui:main@sha256:d8c660b9a3cfbbdb8e8a16839a818ecedeb04183069a956bcc40b09523aafdc2"

otherParameters:
  port: 80
