apiVersion: v1
kind: Secret
metadata:
    name: s3-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    s3-access-key: ENC[AES256_GCM,data:pO8d1g34DBYyhQlGflP32egEBgE=,iv:PrpdK7k9MZ1RrbPNzQJdb9r6vhtd+zN0AHja3Vf1mxA=,tag:naEf1RxX4IwJHHa+HsHmYg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:0GQ043YgTdQNf8MWcyK++knZuyy+cKcHyJxYsaP8ePssh8aSnXOjaA==,iv:r98xZIvEVDIqKIA5eU/hrDrgs4nCt4YQyFggV40b56Q=,tag:onXeu26zUGX7eLk3bn43vA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVmh4dVdTejR6cHU3QTN0
            TW0yTUJiVlZZeEIzOHFWZktUTlZzUzVnWmxrCjVYT2ZacFkzNm0vWWxpK1Z1ZXdi
            anVLOE1lT3AxcnF6VThybzhHTlExV0kKLS0tIHlqRVZEWU50ZXYxY0l6YlZaRGxT
            OFo3NnlRaHFPeEtvVDdqYTVBU2w5d1UKNdf7mnMUJEZvBKiMk3NRJ4e/Tc2AVD7d
            cY7ECrJ2htOFOpF8GUNPKALli8AxqJiZR5SdFWSC1/ycQWxohTV7aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T09:22:32Z"
    mac: ENC[AES256_GCM,data:GL//P+i4+2LUh3DzmFqFKbpv7g6f57KlaKvBB/X5vomlw0qnOuFiFMUW0/Dheu2677ivk4Nr4+QV7ke97FIdaS6Sht1hnnCBoCuJG/0TLJjdJmygz8QgsiasgaSIEtjJAmjiQle3Ql1qHIGE+vaTSDifhvuk474QiYf+8r/69X4=,iv:uEQbZsJLWXkgWhXjgmF/2y2Zi7ZNW44Mg9pGmEDeM1w=,tag:2O5gZFBteN3NpOn0v7NznA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
