apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucq-admin

spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - eee101.tokyotech.org
              weight: 1

      containers:
        - name: rucq-admin
          image: ghcr.io/traptitech/rucq-admin:main@sha256:8025c1ef30b2c81d9e48a537435972515dffa7534d8b2e755d94aeec65a07e66
