apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucq-ui

spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - eee101.tokyotech.org
              weight: 1

      containers:
        - name: rucq-ui
          image: ghcr.io/traptitech/rucq-ui:main@sha256:5d6638ede47f171c9a8efcf306c8bbaf8ee24df656f4913907f4fe19d72128b6
