apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucq-ui

spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - eee101.tokyotech.org
              weight: 1

      containers:
        - name: rucq-ui
          image: ghcr.io/traptitech/rucq-ui:main@sha256:607bc6c0b42eab5d8e348093e3d35e82dd4e160df1892bdf97d03aafc6207d9b
