apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucq-ui

spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - eee101.tokyotech.org
              weight: 1

      containers:
        - name: rucq-ui
          image: ghcr.io/traptitech/rucq-ui:main@sha256:7d640d56cf9af8db9b5b272007f080956aca7ae385652461f4cdcee3dc3624a0
