mode: single

repo:
  owner: traPtitech
  repo: NeoShowcase

webhook:
  name: ns-preview

tls:
  secretName: preview-ns-tls

host:
  base: ns-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/ns-dashboard:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/neoshowcase.protobuf.APIService`)
  service:
    kind: Service
    namespace: ns-system
    name: ns-gateway
    port: http
    scheme: h2c
    weight: 1

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/ns-dashboard:main@sha256:2d59c9d7f54e9ad8d4db386c3c6d42900153f8a9dc82f4d34d8929f09ce6b9a2"

otherParameters:
  port: 80
