mode: single

repo:
  owner: traPtitech
  repo: NeoShowcase

webhook:
  name: ns-preview

tls:
  secretName: preview-ns-tls

host:
  base: ns-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/ns-dashboard:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/neoshowcase.protobuf.APIService`)
  service:
    kind: Service
    namespace: ns-system
    name: ns-gateway
    port: http
    scheme: h2c
    weight: 1

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/ns-dashboard:main@sha256:6c1342da6b3b2b3c5f66224762e95e91a79b08a4c3a1af4b79825b50f58d6beb"

otherParameters:
  port: 80
