mode: single

repo:
  owner: traPtitech
  repo: NeoShowcase

webhook:
  name: ns-preview

tls:
  secretName: preview-ns-tls

host:
  base: ns-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/ns-dashboard:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/neoshowcase.protobuf.APIService`)
  service:
    kind: Service
    namespace: ns-system
    name: ns-gateway
    port: http
    scheme: h2c
    weight: 1

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/ns-dashboard:main@sha256:b9c1fc6a03d3078daaa152a256f3fb1b58131c70e5a999217f8788f0c169ec9a"

otherParameters:
  port: 80
