apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-config
data:
  docker-entrypoint.sh: |
    #!/bin/sh

    exec /usr/sbin/varnishd -P /var/run/varnishd.pid \
      -F \
      -a "$BIND_PORT" \
      -f "$VCL_CONFIG" \
      -s "default=malloc,$CACHE_SIZE" \
      -s "image=file,/var/lib/varnish/varnish_storage.bin,$CACHE_SIZE_FILE" \
      -l 80m \
      $VARNISHD_PARAMS
  default.vcl: |
    vcl 4.1;

    import std;
    import cookie;

    backend default {
      .host = "127.0.0.1";
      .port = "2368";
      .max_connections = 100;
      .probe = {
        .request =
          "GET /ghost/api/v4/admin/site/ HTTP/1.1"
          "Host: blog-admin-dev.trapti.tech"
          "Connection: close"
          "X-Forwarded-Proto: https"
          "User-Agent: Varnish Health Probe";
        .interval = 60s;
        .timeout = 10s;
        .window = 5;
        .threshold = 3;
        .initial = 5;
        .expected_response = 200;
      }
      .connect_timeout = 10s;
      .first_byte_timeout = 90s;
      .between_bytes_timeout = 10s;
    }

    acl purge {
      "127.0.0.1";
    }

    sub vcl_recv {
      if (req.url ~ "/clearcache") {
        if (!client.ip ~ purge) {
          return (synth(403, "Forbidden"));
        }

        ban("obj.status ~ .*");
        return (synth(200, "Cache cleared"));
      }

      if (req.method != "GET" && req.method != "HEAD") {
        return (pass);
      }

      cookie.parse(req.http.Cookie);
      if (cookie.isset("ghost-private")) {
        return (pass);
      }

      if (req.url ~ "/(admin|p|ghost)/") {
        return (pass);
      } else {
        unset req.http.Cookie;
      }

      set req.url = std.querysort(req.url);
      set req.url = regsub(req.url, "\\?$", "");

      if (req.url ~ "(\\?|&)(utm_source|utm_medium|utm_campaign|utm_content|gclid|cx|ie|cof|siteurl)=") {
        set req.url = regsuball(req.url, "&(utm_source|utm_medium|utm_campaign|utm_content|gclid|cx|ie|cof|siteurl)=([A-z0-9_\\-\\.%25]+)", "");
        set req.url = regsuball(req.url, "\\?(utm_source|utm_medium|utm_campaign|utm_content|gclid|cx|ie|cof|siteurl)=([A-z0-9_\\-\\.%25]+)", "?");
        set req.url = regsub(req.url, "\\?&", "?");
        set req.url = regsub(req.url, "\\?$", "");
      }

      if (std.healthy(req.backend_hint)) {
        set req.grace = 1m;
      }
    }

    sub vcl_backend_response {
      if (beresp.status >= 500 && bereq.is_bgfetch) {
        return (abandon);
      }

      if (bereq.url ~ "/content/images/") {
        set beresp.storage = storage.image;
        set beresp.http.x-storage = "image";
      } else {
        set beresp.storage = storage.default;
        set beresp.http.x-storage = "default";
      }

      set beresp.ttl = 1d;
      set beresp.grace = 1d;
    }
