apiVersion: v1
kind: Secret
metadata:
    name: crowi-swift-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    CONOHA_USER: ENC[AES256_GCM,data:lhbChoCM0wM9xGDU,iv:vruVcG2yjOg3Ny+n8vkh+R5LoO1oXDsFKEOVrYlyc7s=,tag:ijCikchiWP2nk/lgyq7hlg==,type:str]
    CONOHA_PASS: ENC[AES256_GCM,data:ezL1VNi9wBUDnDKq,iv:YgihQQxckt953//gLyj5B98rn2gN2sGJWjUmhTT5iVU=,tag:pukPupx732XP2tsx78tL3A==,type:str]
    CONOHA_TENANT_ID: ENC[AES256_GCM,data:Ajzct5taKLNcFBDAwRiehBVV6OphjPIt/HCRHgPRUY0=,iv:eoP7WUK1n7+5lTb9N/ibkVXbIcY3F9yvowq3LzUiDWo=,tag:TV8oRiVK9ByGlp38riFY+w==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK2JrUXdrVmdrNTg3dFFy
            NXltaEo2amlUTEVsUkFMZDJmd3NrdmtTR1Q4CkJubE5VdFdDenFvSExTclBGamVC
            MldmdExGN1ZJMFhyaCtWS3hUT3hjWFEKLS0tIFFrSFY1LzNwU0s4Z0tiS052Smpy
            eFhqUERKV3ExWFBwUFVMQitXaElCWFUK+iKhK7r3OQwO6D0WZvbsh3y6nuAK3vri
            jKxfBRrkk2PFhXoH5mlx2qDX5wtO4B1BO0vc+x481UjIl8sOiqmUGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T16:16:02Z"
    mac: ENC[AES256_GCM,data:IxWNoBXAMlT9jPyQhfTlvJD01vHFE4D03IdO0c9vaMeq6uJ28C5cSWcMScnwjgtmevj0aGViFz7rPS4Mj4icoOTZwS9l2fvjvILfK8fRXxgP4vrtOAPX2XElC3XMvFkXZ3h61H9/sOrYjOAKTxI5EoOJi34MUmo9++V64CaczJI=,iv:z93Cek2yfe8EGFrozj5aQlrcgX0ggdEXBAcdnvTO1LQ=,tag:BQh2w/X3jHs6RhKkGKS55w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
