apiVersion: v1
kind: Secret
metadata:
    name: loki-proxy-tailscale
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:hXMIOp17fbUrS1KP7vWDhyi5EgAKr+uFAg3ePKm4HwN2WBV7QU3XxDQJ9J+9ByU76I5cxuWKnDmjHiCvTyU9Gftq5HNyCebMV3emsSkw4aM93Sxuglpz8A==,iv:8cyyWDjylbSoj8z6FZw/yUfZ8cX9TWxea9vVuKsKWF0=,tag:3Q/JZvkuHeQubHC8hp4VGw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1alV2QkxnWTd3WmxQNlNX
            bThTY2E4cUVFazVwSm1xTGRMSkxLRERId2lFCm5tQlRqSUtSVHVlOGJRWXV0T0Rp
            bm1DWTl1UHpqMTE4TnpBdmwxSkRmY1UKLS0tIDhmK1BsZ09MdW0yaE84OXErbVg4
            TUlTRDlHdVBkUEI4Q3RhUStFM3FDeW8K9UzupVkQXSgPDLbJVwQtrkUrGb1zxkzi
            O2tljlgeC/zCIb2toaGuMQVhgqiERZDpkTd5ARFz8/vDOCpXtMpZPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T02:40:38Z"
    mac: ENC[AES256_GCM,data:fMD0y2XDJW3yhiIoaFg1loOV07X74oHXirQ1NKC2yMd//aJ8PlmOIYAv+L1P8+3m0fXEbmIOk0Qc3smCidmmqFQmQ8E1SE7LxcnX+0xrLxkvmtys6qBZ360vuXtb//ZllzKmkcjgBx1y30NRSTOmPjPiSedZS6RIEsNySKsTtfM=,iv:Txsp0GmraGScsG+bO1ZZIIqR7Dzd/OUqWdxdSTTpYX4=,tag:CVKZB6Kxoovu7IC5dNX2Dg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
