apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics-proxy-tailscale
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:b7gh9O5V0vjWL555v3k1vv760F14+ArtUNFHpLqEg1BR2QZBdssL6CPlBG2ayfHooo6YfZhpoB+VZDoHLVeuMaFFIpntyd0EcaoNlJBgCHWJ26TNyRy0jQ==,iv:lTf5bAWwODoSDud4ieaIT8Kf217RZmss9kQuYal3N+E=,tag:V0RKETxHwdNholbenpsCFw==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ1NDbU9zWitYSWxkK1Uv
            d1E4VFZZQkliNGlFOEcvdUZ0Q1M1eC8vYmpFClYzYXBqODNuclNTTXhmaXM3Qit0
            VWc5VWV4MVF5MTRaakRtQThyQW91cVUKLS0tIFhtV2lYdWRuTldITHdVTXE1VVAv
            TVg2ZDdmR016SHBqQ3ptSTVOL3RsRzAKkTuQKOEAe2maZ+089lQvCeY10guY2zZI
            f7nHwIeqJNo0TV4YpGD/QVs9DKAIqUEsyuPualiZiLGdVacrLRCL3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T02:40:47Z"
    mac: ENC[AES256_GCM,data:sU46rnPShN3wfrxGZe+v4twpysHzeg2cg5CF7hlE8+ohgv7t9fs8YRk3VSOLRls/yI6m0CjwXrmNEOqWTvTEQoZhMlydv4y/QepDf40FqKUK8tMe8OJZKKwreC9b/3TnESQNBRssdi0fXR+IBfaLCj4gc4sGxyZFHeCdD0i7t8s=,iv:wJKFeGm0wa8iimn+MZm1IEuRYY7xVvdELTpiOslZcvc=,tag:4fF/N2o8nK8BZ5TZxAJd6Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
