apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-widget
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: eee101.tokyotech.org
      containers:
        - name: traq-widget
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "20m"
              memory: "64Mi"
