apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-widget
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - s512.tokyotech.org
                      - eee101.tokyotech.org
