apiVersion: viaduct.ai/v1
kind: ksops
metadata:
   name: ksops
   annotations:
      config.kubernetes.io/function: |
         exec:
           path: ksops

files:
  - ./secrets/db.enc.yaml
  - ./secrets/nc_secrets.enc.yaml
  - ./secrets/redis.enc.yaml
  - ./secrets/s3.enc.yaml
