apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://nextcloud.github.io/helm/
    name: nextcloud
    version: 9.0.5
    namespace: nextcloud-dev
    releaseName: nextcloud
    valuesFile: values.yaml

resources:
  - certificate.yaml
  - ingress-route.yaml

generators:
  - ksops.yaml
