image:
  registry: ghcr.io
  repository: traptitech/nextcloud
  tag: 29.0.4

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - las211.tokyotech.org

nextcloud:
  host: drive-dev.trapti.tech
  trustedDomains:
    - drive-dev.trapti.tech
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: nc_username
    passwordKey: nc_password
    smtpUsernameKey: smtp-username
    smtpPasswordKey: smtp-password
    smtpHostKey: smtp-host
  extraEnv:
    - name: NC_installed
      value: "true"
    - name: NEXTCLOUD_TABLE_PREFIX
      value: "oc_"
    - name: OVERWRITECLIURL
      value: "https://drive-dev.trapti.tech"
    - name: NC_activity_expire_days
      value: "30"
    - name: NC_trashbin_retention_obligation
      value: "7, 30"
    - name: NC_secret
      valueFrom:
        secretKeyRef:
          name: nextcloud-secrets
          key: nc_secret
    - name: NC_passwordsalt
      valueFrom:
        secretKeyRef:
          name: nextcloud-secrets
          key: nc_passwordsalt
    - name: NC_instanceid
      valueFrom:
        secretKeyRef:
          name: nextcloud-secrets
          key: nc_instanceid

  mail:
    enabled: true
    fromAddress: drive.system
    domain: trap.jp
    smtp:
      secure: ssl
  objectStore:
    s3:
      enabled: true
      region: ap-northeast-1
      host: s3.ap-northeast-1.wasabisys.com
      bucket: trap-nextcloud-dev
      usePathStyle: true
      existingSecret: nextcloud-s3
      secretKeys:
        accessKey: accessKey
        secretKey: secretKey

persistence:
  enabled: true
  size: 5Gi

resources:
  limits:
   cpu: 500m
   memory: 256Mi
  requests:
   cpu: 50m
   memory: 128Mi

cronjob:
  enabled: true
  type: sidecar
  sidecar:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  host: tailscale.kmbk.tokyotech.org:33060
  user: nextcloud
  database: service_drive_dev
  existingSecret:
    enabled: true
    secretName: nextcloud-db
    usernameKey: username
    passwordKey: password

nginx:
  enabled: true

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: nextcloud-redis
    existingSecretPasswordKey: password
  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - las211.tokyotech.org
