apiVersion: v1
kind: Secret
metadata:
    name: codimd-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    CMD_DB_URL: ENC[AES256_GCM,data:N1AmYrw3sDY=,iv:co3HQ5jlUrvzLooFCb4PEf38eAyoINuA88hgxiq7FLQ=,tag:hHRQno2hZ3HDWi3CFhXKxg==,type:str]
    config.json: ENC[AES256_GCM,data:l/yhRS2TaEwkSRpQjYsvN7jrJ7tSYISwWAxW/Gu2XugtU1TIFiyx3yedaIX2sYulpZ+3Iiut45oo3k2Cc6lZMplOdMmuvOH0zCdI2PXTFvzsAur38Y1+4iotgknLRsNtGzgE/dTadAaR8eR3RCBrWTWwlcIeF/54D+1yutxgE0p0jQokvEfwATZvkBmh6Q8Q6e+ziLX8uBONanHENXfAEonF5mlWPTn0qAvKUD04tPZd24G1vxyg6jiU6isq67Q6psJL5CIUO3g36UwhFAl7xhJ7HyVc7jDp43Lgf4zugoyboUY/H/XTuJJXuBAVU72qkKgIroVJ+NM4dlifgB3TyEg9rFzR0+ri4guXgPisqhFgmXiJ8hPMWVhrArtw8Qy+E6q1IM21LdJuLRgStCHFJauYMXNJQhrU1YoPxUTYD6oA0LqfOeTW259TfUnhZSkXQZVjnMgQK7sJ/64SVnRELXCR6T5olyk3pvupq0qqrRjo4VBlx5ThR24nMxDJI3SRFoRzVX5dPnT+W9bc9FKGwdPGpLaNRmlMKhU0fooIsaMdIH6UphpGUueTiKc3VOxRvZRVNZJ3jd6bhLo/Diz6foIqxwpTrgvF27lufsIlV8YtwgmgC0PhKheLJ6ASYi8BhJV4xjxXw09Aw2p1EUn369lU+HH7L64AWa1SdmgnV+E8K0Dq4IRxbyCAZwdvzrynw+0XIPJScx4C8LdCXXI91Rx5pIbxEnycVpyHiFKfkOzMRMSQVH7Q79getu71LLDKtJvTRmDJwpXbSXsfzYnRO1MXQIFzMtUx4wZZOdMlgYzFXz2g9Vg=,iv:TRCxMhizUPKgLdGpvXLZGKFOTjO/Z4lJ9JbeHinjlVc=,tag:Zng7lgpa6Qhu5v2BD78aEQ==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WkU1dDdvYXc3ZUMyQVdR
            dXZQYzhnNzFBSHhjT1lFeXRtT1NKdWU5TkJFCmk3NUl5NUpQbVNnYTZ5WlRjUit2
            M1NlRFhYeTFUdTBZN0lIQ2lLeGNseEEKLS0tIExrWjlSV0VmZE9OZ0RmaktkdXEw
            TzZPajhoSUtDTGdhdmRvMkxhejVCaTAK7bCFImS+wdhAOrOuDMnr7AYldldk0EcX
            3OlfilyLzOHCRXjj4+9iWVKk5kkdWMTVWO2gzR55YynII6uCu78uRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T05:16:02Z"
    mac: ENC[AES256_GCM,data:kxzMfiNR6mWKzs3pQ++obRCk4IqrCh9LHHejAacfTdesOQjKB5qUxsadKJVhbPbEHP9epPj8BqCkPm72X+3W5aEV6YSocYV5CRYlUQ+wgCOD5THQeIGfTcq49YnOlduB/NTxer7sMg4KLHkPvjsqbmdX5EAJkEHU3NdB9GAKMKk=,iv:FqtHFSi6yoRt4aDIu6IPUojV7QA6oCDFDCUlP9EAERU=,tag:/uU5G6tSHO/1sMrUrZ1qlQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
