mode: dev-and-prod

repo:
  owner: traPtitech
  repo: traPortfolio-UI

webhook:
  name: portfolio-preview

tls:
  secretName: preview-portfolio-ui-tls

host:
  base: portfolio-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/traportfolio-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api`)
  service:
    kind: TraefikService
    name: "portfolio-ui-{{ . }}@file"

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/traportfolio-ui:main@sha256:ed7e58dc356a9837bde498da10f6f6b7a9700e928c52c45ae70cc6a599e83fd8"

otherParameters:
  port: 80
