mode: dev-and-prod

repo:
  owner: traPtitech
  repo: traPortfolio-UI

webhook:
  name: portfolio-preview

tls:
  secretName: preview-portfolio-ui-tls

host:
  base: portfolio-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/traportfolio-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api`)
  service:
    kind: TraefikService
    name: "portfolio-ui-{{ . }}@file"

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/traportfolio-ui:main@sha256:1aae3aacd6acdf18b5c810f997b257066a5018a089c85d113087e5572836bf8d"

otherParameters:
  port: 80
