mode: dev-and-prod

repo:
  owner: traPtitech
  repo: traPortfolio-UI

webhook:
  name: portfolio-preview

tls:
  secretName: preview-portfolio-ui-tls

host:
  base: portfolio-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/traportfolio-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api`)
  service:
    kind: TraefikService
    name: "portfolio-ui-{{ . }}@file"

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/traportfolio-ui:main@sha256:51c4212fcceefee3e535160c610b7958ce02b9bbfe74d872dde2a3be58aa583a"

otherParameters:
  port: 80
