apiVersion: v1
kind: Secret
metadata:
    name: vps-api
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    bearer-token: ENC[AES256_GCM,data:uMvrCD1I87tYfdLD8OoauGe/BtOydEvOklqHJcUiskc=,iv:yY7xIF1C/blLHm1gwWNtfmpsRNNfrA+yIYubEzU6Tuc=,tag:tJAZ1b5ZqOh4kopzNl4jUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMzkzK25qZTRYQ2FoZ1hL
            RXM5bTkvMnpEMzZHU1N5TTBTVERNUWJ4TFU0CmFGaEhNSGJYTko2cStqNHlLM2xM
            TSswZFdiUlBNUkdGYytaQXhNRXo3U1kKLS0tICtuREpxd3FiME9mTEJaekREMnZ0
            UGlhbzFhUzJYeTIxZW9NY1VLRmlnakkK16Cg2hQntb6B1VheVCrbSoa0zz83PMfq
            l3BhSvgaWRu/7LP2QM85y4Pv9/awvTRcQA9jEQPTvDPJ4/s8nl8L3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
    lastmodified: "2026-09-22T06:06:11Z"
    mac: ENC[AES256_GCM,data:TWcoekBykNojFrDVlCg6TAjrId6QjEu/MbHdIO3693Z+rsywYDXOL2WDxpykMXh1I1XhlY5ExE2QcgQrGaQ2JoUYHLWXesfBVMnnkadrbenHIHXKOhEja/wBNvgoZs3cW4n7jfqQaq7N+z4gjH4yF9U5TyHFnZYUtHU/j+LwV7s=,iv:1oO+GsSH5+8wMoXlFa4xZiNx3nh0+LlJXFvaKkWTIPc=,tag:EmNVyqTpGmn4hpUek0mMOg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
