name: Format

on:
  pull_request:

jobs:
  format:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Node and Prettier with mise
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          # renovate:general datasource=github-releases depName=jdx/mise
          version: "v2026.10.2"
          install_args: node prettier

      - name: Check formatting
        run: prettier --check .
