name: Format

on:
  pull_request:

jobs:
  format:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Node and Prettier with mise
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4.2.2
        with:
          install_args: node prettier

      - name: Check formatting
        run: prettier --check .
