apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db
stringData:
    username: ENC[AES256_GCM,data:iy6Dn4hnkDSiRdZI+WDGHcM=,iv:Mxdo5kb9oW1UtDN5Yi382ozt48LlpD3wgTgYhoOBaJE=,tag:o654iq4QpyO8qBPHP/bB4A==,type:str]
    password: ENC[AES256_GCM,data:t0NGV8DlaqEJ25aKdT5PhdO3fk4u9fDhUS7EGeZPuZNJC5GIgW8ledbZ2a3tqghE5Vqh3SXrKFu/PoOi/6USlw==,iv:ggYZnrcqxiL8Ng1Goj1JvVMMSHesUceS967x4AijwEg=,tag:u8b1II29FGLF2yLjx5f4jA==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdEphNk9CNE50SGpsMm9L
            cFZiZmpjL3Naai81cWtiYy9kYkNxYWJTM2dZCktsbndLYkd0eTlCM25NV3NTNUhk
            K0c2TlpQUmJBQng0YkEvaDFGWFE4WjAKLS0tIEN1ZllTQkRvZ21UN1pQMlR3NHFX
            ZHZFS2FaRnpRN1QydDdqOEg1S0x0NUkKQhi3qfsnYPJWZhbrYowYhMMBihYvBw0+
            QUOsrNlW+W4iGx99jCXeL2RtR4s1rKOA92JUL/B2zTF5t0bd0vhDLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:01:58Z"
    mac: ENC[AES256_GCM,data:Q2TNWWpVcZZdN4U1Y6gV1C0uuWUx3hbk2ouOvzUToL2XZ6sJdv//TnayC8a2sEAr8ZPW+mItTzVwXkmzeiqnJCr7fcwFF0h1R5mVwfaa/nyyoRN0ElZbaPPyBY/YfxM9SkKysv7A2L91AepwIEVFHsG6NwYhOxhiTm68VTSI/4s=,iv:6MObVf+7M/j8BqtOUFbe+JHcSvQFcX1wVVfc5eBjfJE=,tag:ROCLpUjCcUJwcsJyR+Sasw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
