apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
stringData:
    smtp-username: ENC[AES256_GCM,data:6+ueHjXN,iv:SAnLdSdWKLCQvRqsWn6kkCAKi3EPOvS2G5kZZBSJKNg=,tag:LrZHmJ4fDIHM5YX1SoI4YA==,type:str]
    smtp-password: ENC[AES256_GCM,data:nTIqXXTGkxfXRxVgXp5+O2meXLAdycPkxcciziUO283NEnKTLgRGhT7wrzsEoIsokhucTcSFby/fWStuHTiFcSeuREOx,iv:NVUrd8rBBglsPcLeLejP4NTBbwwF4MRR0eVaRPmrbc4=,tag:WWmcTCWlEpowzB5k0u14Yw==,type:str]
    smtp-host: ENC[AES256_GCM,data:8WNpCni5OkIauMOL9IrOiqk=,iv:qMskSY4vpPMBEd2HeFZYknP4ItGfILUvoDSN3yCBqBs=,tag:EybMtkgO9sEOQX/KbvRARA==,type:str]
    nc_secret: ENC[AES256_GCM,data:EklM9fTTELRUoMeWE4VusknyNzy0Qr6AC60uDLhHFB6CReyNQdOsezD76QAZaiFX,iv:irpR5lJInCe5GPaiEGOru21Pdnj5rlAT3TTa3TVSVis=,tag:MOkuTd5CWFIQ8p5w/OxrUw==,type:str]
    nc_passwordsalt: ENC[AES256_GCM,data:6OPOMZ9tHqaYRcQbIMDVb3HnlhvCuHyNZRnbX079,iv:TDNQsMsJ4UvVjoqC0/9oTENF6BY348vTWiWyzJR4qI4=,tag:z9Fuz7OdhPhQ3jrP4weIDw==,type:str]
    nc_instanceid: ENC[AES256_GCM,data:x6pJt5Ur1yeJZuCN,iv:NsyAKfEwipoV3ksSqhSVQar65VuhseRuYhizZER5onU=,tag:WPqSFTgnX6+ipO81a9aHSA==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsb1ZQd203SmZ6TWhFR2d0
            ZVhYZUZIWkc4VEZzTXZXU0Frd083MmJic2tzCk5DK2cwRjBxTjdEVkswMmJLUUg5
            L2E3RXVIalVtRnZJM0w4d0swMitWbEEKLS0tIDZLM2FiM2xHbTNSdWtUck5jL3Fl
            Um52OHViRkkrRFNZTGFNQkJnNUhNZG8KBBsPpDe8pwAm32dhSMB0GhJRzkMb42gz
            htcty2JDLYcKkkuZJBKA+xwnAyYVtxXrszROjVZT6GWPjKy2EarDwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T01:57:42Z"
    mac: ENC[AES256_GCM,data:HTYi2lnpjLq9i/f05QsrabQwfeO/krfDNsCZ249vdxTx+8R90Q/5ZhltDAJK8whkYfIMnY8ZP6ZmPecpI5JUHav5VpBdQXlRUkCFikjjg/tn9N59sbcW0sQSLZ+wHuYXoka0aRidn77PY67KtEPbzUImk/XZ/tJmldOyA+/I1Gg=,iv:vKekKeotjwTVtQT9r8g3yVsyjh9pTZWYeVSR9p/uJcI=,tag:FzY5tmLWqUjs2wLvIYKDjg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
