apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
stringData:
    nc_username: ENC[AES256_GCM,data:KNGGNQ==,iv:D4LttWpDZdTZDfIIVlandxP3xMShFKOK6N1iRdmQVSc=,tag:DRXD/devnZAc+b6x9HfaEA==,type:str]
    nc_password: ENC[AES256_GCM,data:UXLDn7+PH7Ymwr2hvMxl,iv:Br0oG0ZG8rBeaeZpx2FjQMigSz7nla8lxCHZOs6SNcI=,tag:uJYzCxZMMqipj2R7FLxizQ==,type:str]
    smtp-username: ENC[AES256_GCM,data:LZCL3/pa,iv:2vHQkYPbZ7aIoq1VMToKMnwNTpp9BAvnNCviPSmCrJ4=,tag:A25uHXvsrACXdJhgKiL0Fg==,type:str]
    smtp-password: ENC[AES256_GCM,data:j/o3FV2VJJSClsbxQEv6NKfv11mwQfi6AOg/hVE61bQV0zwCgjUKITQRfsuDdoAqCiai7gEf0u6THVOXYktkKikPLQ43,iv:FYIJW0bqhZBk6YJkA2jxG2XaXFqGZRj3Omp05/ILEkQ=,tag:b3pgbJs5seFw7Iy2tFW8NQ==,type:str]
    smtp-host: ENC[AES256_GCM,data:IeBPQX4bfg+ePrSkcg6WHDo=,iv:gcu6an58AdGTeSInMflYjMkqrzUbE8nMbRMyZkBECaE=,tag:MY/6dNQK8C4Y0d5+/QHhQw==,type:str]
    nc_secret: ENC[AES256_GCM,data:NBN6l845rH+s8gxsobiIrhCi2AC3CdKR0So+oAzlyEXP74bPFg9KYlLdxtTS52Pq,iv:QoeDNfuu71tyxsAgFDDqnPsRbMjBnWP/lfh4ynQBL+s=,tag:CBeMVLTTyghOiYLN+fg2SA==,type:str]
    nc_passwordsalt: ENC[AES256_GCM,data:Iu+/+F7opYuEf+rg6+GgCNMk9OW/EGlgTj2QVQnr,iv:EXdtz17b+5aDQt4x8R05qIrijajsfWkafoyCirSa2O4=,tag:DQeQe4eMT/nvMKUAE9mvGA==,type:str]
    nc_instanceid: ENC[AES256_GCM,data:UZ/w34wdRmYA9OFx,iv:EhWPzKtzbqvC3oexaKOyl9sgQAhm5JfS/Be58iJViBs=,tag:q5t6HoHaY+plBzjf73+Bsg==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cHBGallnZ2FWVnBZWXc0
            WWwvaWtnUzM1M2ZUN2RSZ2RkKytCdWlxcFdJCmozK3dKQ3VJbElxUlNFMnNOWSs5
            RzBsRTE3ZUJVS09lU21WN29Da0xpQlEKLS0tIGIxVmE4bWVrK3ZEZEJodVZDeDlS
            R0NJbVg1NXBnM3Q3bmgxSUZncUF2a1UKSzzPQpf6BV5NHQix2V6/S/ptPt3D2xdD
            DegvkqvAIwlOvuzYS8/T8GDr6isMpOC9lTqlYQYpWVMO8IznKYUxsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T09:40:46Z"
    mac: ENC[AES256_GCM,data:CBhSPNwh3Og4lwLEQ/S9u+8+4wxzbaXbl1TGB+2p+xTtCFYPFLzOrVZUd/KS6Oi3RMlpuqV1MfixlsVnhTYZF4kIsbBPmX9UuHVOVn4U0vRyhQlCa3nMkxUEZWl8tkc8d2YKAhKJVOVUU7Er6JkoxeJGVTirrjmdaKC5Zhm8QSA=,iv:zxHk6eNHfSwb0ArpgbGNJV1IU3UdNNV6tCm/GtP4n3w=,tag:T/uD8sa9Lk2dZPshZj0LvQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
