apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-redis
stringData:
    password: ENC[AES256_GCM,data:kBa/OEdO5D00rY59+M3fwrMd3iyfj8Pr,iv:Hb+mzTLW7nkUy48BwQt5qfrwK9VK1WrqkX8pZgR6MsU=,tag:1fp6zij/nmpJU5oT19dNuA==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmalhMa0hSTjc0MlN0TDFu
            dW1iMnZzQmhPbkhmcFQ0cWZ6RVdGMVpVNnk4CjJDZUR2RXA3RmdCSGczVnQrdmZF
            V1Y2V0tYYjFKRzgybEVJZjVTcEd0NWMKLS0tIHVmdVUyTWtoUlZ0bTJMekc2OXNn
            RFRqN0Y4SytheUloVXo4UEFEZzN6R3cK1wLI68nqxh3Utno83V2n0SQ2HSRr1zjv
            t5ja1bjqCFcX7RotPdk6LJiYGTNiXkMqgaxGN0g7xcw0aeD/stBBwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T10:54:57Z"
    mac: ENC[AES256_GCM,data:8Yh6v7KSuyeMl4zwvXsy+Ttv+Xk/Aw4bMyPtB0H8AbUTD8ObjTKfRwL66+q8/bsCrbB5kdAMZNX9G3zNrwsasVMJIcl3RpcoBHYjaIwWVMemUde7ZKZz2zKphBOlFccAexR03HD7GV/IZKOqcjmzBLf4fD3mIfReWztnngWSnVI=,iv:zS9fTsDLE4tgq1Fov9g5HudNtm256JkR/WktkGNMgCw=,tag:NJxhPO8Rmtwj0XsbqTwjCw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
