apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-redis
stringData:
    password: ENC[AES256_GCM,data:T0GPBfsBCjjY0lIW74XTdew0EkAvq/9D,iv:40wjJm1msMLIQD9nJ+uFn0JPSexdt+W9QrvqvDTQrRc=,tag:UnRF7HPQMjw9np65JoXb7w==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbGxaalNUeGVISnBUNTlj
            MXBxYjJHS1p4OWZjNjMyMzlDbTlTMmgraVRvCnVsY2V2QlNsMlI3TXg1UjA4OG1R
            NVhXd3MrT213NmZ3ejIvdHhkQWVnYWcKLS0tIGtsUDRPZU44dCs3N3pXbnBqL0FU
            UGszNGR3MGUyQjRYc0tnTFpLdFRoRlEK0KWNUKNeTTqBmwV+HqY5LB0kotAc2MO8
            XN6RDaW3MkQZJAZjpNo3dLxUVk9tqHSmfc8hT+Bql+tqsIIuSZTLog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:06:51Z"
    mac: ENC[AES256_GCM,data:3hUFvvR72HTxPEPPb+uF2AU3bzmJ/U7Aj9CxhHQ+rgTPM7VUfXPcU2VhYNrzdCf80G79btjjwwBxviqDgaoJySUD7lr/SBPxI3SVZbYbmiJZR/IK3UQBGqVzLQUFxP4IkNzWknZ7+2BOzAZ6q0ufNA5NAtyAv5T2Z+7WnsnF3ag=,iv:VT6B7mWjCAvv/9eJDOHax6YnR4rhvuq2XPq7tA1Bb/c=,tag:g8da6QiG/zf92CewOMqphQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
