apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-s3
stringData:
    accessKey: ENC[AES256_GCM,data:1+6suP8aYFe5KTqM9ASJBxul8dY=,iv:yj18MO8kPWyUqBG4uls+xVlkyRb/JT3gxbGFGiYS/v0=,tag:eGbfIcwxUNr+zNM8CK3shg==,type:str]
    secretKey: ENC[AES256_GCM,data:Z5nhKnTG2WDrL43DxsRWHIlX5BLfrJwP3aeDCkmziFZN2i0M30osUw==,iv:xDt262o9ZVlZF3d3/AUCKzm/5yG4XBXSeKdtEuMt1J8=,tag:gyXpzLv3oFcs/nvGc1PXCg==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUsvcnpyOXZHeUhvbW9u
            Z1ZHbVpKMC94SjVuVi9NNHFJdnU2SVdCa3lnCkJKanloVExtZ1N5cWpXYzNkbVlu
            WXFKNGY4Tms5S003enFhTUNoOSsvQ2MKLS0tIFh5Mm1aVm01bDQ4QnBkek0wRkdS
            dXlKMVFYMS8zcXdLTU45YUkzZ0dFR3cKDqyfdDOnvjRBk22NlAwFRm26nhHXGVI0
            29URCPz7wlz98sUL7bExf4abIVgSQvqV2wgKELAoxQQhciQdBf3hFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T16:14:13Z"
    mac: ENC[AES256_GCM,data:0jegGAyBsFYfm0b7T9LVXkdRJnoDG0zqlFlpfY5a5k9s814qHsPpXoXE4cQywbVeTZAU8xzB6q+Fe16zPSGc9YN20UiKtSGZOyjKIqjboD2G4fmWkibv9/xMc+2FAXtvc6/cJV1ozQWBxVdFkpNpKPGwHuiIcfYle7H0bBBaiVk=,iv:FD+zHydMxpj7Nh+u5zbGSxR/Gnet5kX7zT0ZFCtmqYw=,tag:YO4lgiG0cJDV7J5IP8v00Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
