apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-s3
stringData:
    host: ENC[AES256_GCM,data:uK7NKXSa+69rU4B0lNHzg/wCAeBV1EcpYVnjdfhCZQ==,iv:onKTc4gCSj7XL9QNGagi1plI/9ZFL/S/m5/QBqI0Nzo=,tag:+RkIgiVZggz6BpfIO3eR0Q==,type:str]
    accessKey: ENC[AES256_GCM,data:Aa+znGxHS/FDBST96nZAHrFNGnc=,iv:NtcmNvpmwOpdzS4UFt2vCRcj4TdrpLTFVfew/Ri8C8o=,tag:Jw7QZjIj6BZvBa1nExIqCw==,type:str]
    secretKey: ENC[AES256_GCM,data:uSUGl5YqTkK7ppn9YtfGixR5rvNkwe5VYAZXOfOZk8F3kzUzIN72QA==,iv:GaSVyjz6CZxbALyI35+vpfwcsvcG2kp5K9u72UAD6JI=,tag:k00oW0k6SLRblym9PPW2Zw==,type:str]
    bucket: ENC[AES256_GCM,data:4GjTmPnD33KRh7T46fvjULku,iv:8j2fnvUdX1Kf4mQh9qJRiTJNLkieNKnVtafNEhFkpkA=,tag:K7GOFwgE1jRpQEczBHL6vg==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbEMvTzZRNzBPcG1ZWFVR
            K0Zpajh0TGNNS0dsSjgvdlQ1bGxiYUdXR0hZCkRwT0w5cHFaUUp5Zk8yMUxhSjlj
            UDJ1MjY3M1d1MzEreENsTUpiSzErSlkKLS0tICtETVRpdWptcTVsMklrQ1lYTHBI
            K0ZVOEFOOEtWYjhlYWZFdzZwTVRnZVUK8KOg9TVzfnyYZvwQ0VUttBA++4QUznzu
            bvc0I7RvChRqVRfDgvjkQAQug3EEikLl+IWQKXqxGcRzk9dHIvRCxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T06:08:40Z"
    mac: ENC[AES256_GCM,data:UJvLLVeHBx6XDBA/FlJ8pyVIw/aDqhq5VGCX1GGYbM9KeluWTywp+dczMau04U6UndpkSVvgOLeNrAurrvVAZkVi+6yWvy194fGqVuXNFqd8nhuReqLpkWtDdoY63weMkFpr3LcvjOw/JFXeB1CWgmgfuZZQX/CIzXVmN2f7duM=,iv:Axh24jdzzwkcanLbF6VcM984+XP9g2MmSjLLf5OLMco=,tag:ASB8N2pnxnzyvSx2b+OXGQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
