apiVersion: v1
kind: Secret
metadata:
    name: secret-env
stringData:
    OBJECTSTORE_S3_KEY: ENC[AES256_GCM,data:KXFBS31wIkx3HWKNtAGNYa0QPCk=,iv:/gUN+S285US/5mMAY3qHJDazUFzqHKR0G8gHp8KBsjU=,tag:jPx/jmtSRnwhj2wO2VcHng==,type:str]
    OBJECTSTORE_S3_SECRET: ENC[AES256_GCM,data:dBZahA4gFTZCCk/8Y+opAFEbeDPEbJU/NBj48CSve6U9AQaVVO86+A==,iv:oM8cuFH4YN+ZwMyUdTXzleYq3N1O7ZaYZJwXvyCjFmU=,tag:bdp5XcMkJdpoBUFjxZSyQQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:D7dbLIB/RHbXA3/0x0irgl/JfjDSkJ07ayGxjj2lJDKnxDGc24zVx2RPWzHtO4ZEOJNmg+Dp/HqleWkdjiUV9C2/C/jP,iv:hALQPPl9rAUpNgVpcW/olpQLZh+JvrBgN95IeuMyJEA=,tag:jVMHZHh3JoG6CVZcNCkBBQ==,type:str]
    NC_dbpassword: ENC[AES256_GCM,data:fSQ7KZ/Ci2F/7k0qQkmrAFxJla7EJZMQkGuN1AbopytyiXbHZ+SC9CgguN0Bl6X9mbwpvUNK1rZXgLijEg35lQ==,iv:9XoUxJIp7vsMICkjmiAMRWiWJQk2y7YCV5osRR7422I=,tag:UljTNwjjs1E731M2F8Xs0w==,type:str]
    NC_passwordsalt: ENC[AES256_GCM,data:P3wEs61kOlIF04CyR/C9OZlmXxoLyosH0SRcI/KX,iv:r1qpveyiJqZDhqq4P/wN55HXdDjwLpQ198jGJwot5b0=,tag:5fkaRIMoNt/yDWRLPRGKwg==,type:str]
    NC_secret: ENC[AES256_GCM,data:yvhk/PGV9Vda7r19wlG2aP6Z2DqzeBqIrZk/zYtH+rmis2OS6SsxQA7RJMGOHtca,iv:YgRlPrZNC/k86HzNm2LNnljPL8VEfSxLIdyDi5wGp+c=,tag:NsH1QICFUTsrmUHISJ+QlA==,type:str]
    NC_instanceid: ENC[AES256_GCM,data:BSvse7K6cbO2AbH9,iv:qzLuzclmvSJA4O68v/RbhjyWkEhyRfzovz9Qvj5YWv4=,tag:G5HqigWLbvkcSf91g+gnPA==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRzMyTUxNMU56K2RIWEFx
            bzBJZGZsSFRzVjVvN25rTC91eE5SVktaVFZrCjJHR3dVMFM2L1o4M0VPSFJjQWRO
            cnVha0dlQTVCVDB1aWIxMkI1RlJsZWMKLS0tIEdOaWhXaUZML28zOVZSUGgwSDIr
            RkFjUldIZ1VUNmZJQ1JWYVNXTko2RlEKwiwzP23FfzD0l1Dne+VzHSH610TO9bFj
            XUjfU/1kZEeCM1nXNDlp8QzvQsRLWZnmcSXQyu6FfVjwhWzlEdyfmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T09:52:22Z"
    mac: ENC[AES256_GCM,data:/+Easrk6UgIFnn4Uh/5lds8A64/EoyB45TL8pVdSALdHu94U2BJ92NwrD5rnv2u0kevG5k6bVMrWoX7+o26hfIBrusn7jOeEsJJxPw5YLI7ZEa9gtEvcyWbJpMDQ2QryLCX3FaYKAjgKgyoNRJQhapmZ77GL1wR8V2R2y4NHlps=,iv:53bpUPf1TOPM9+reB58ZhhhV0mfFNrnn5YxznuUC/Q4=,tag:0BmyYeFOQqUjGrTpkbMW4Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
