apiVersion: v1
kind: Secret
metadata:
    name: valkey
stringData:
    OBJECTSTORE_S3_KEY: ENC[AES256_GCM,data:8g/Nv6xJYmk98j1vJ27kzv0bI64=,iv:K76YbRfNV+dxNGlP8Siz/wRqNlpFg6SvbmCGx8xuha8=,tag:jeR9ieWHYDros0hj5Nn/Nw==,type:str]
    OBJECTSTORE_S3_SECRET: ENC[AES256_GCM,data:V91Qu9TAqeFqZHWWxwj7egrZZ8Pe+uTe+xKKhCKA92y6exY4Kzx2Fg==,iv:4igvBvedhCUcD6mYT8oakvSw565auDc5EPtJfD37iiE=,tag:aGNkCujtnMUBhAoQzDW7sQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:LpAiQspReHYL1XkLVVHD/dyWw76sSFV8X72GOa6z2b4qdf/CkMfiKgBmo/1zNep8LaBYsv0Ia/jRFW7O2Hr0mPVxLWlR,iv:KLJYWUk2FZlBVu7ObeFx4S799LQxG4a66J0PL7SPyRY=,tag:D7EDk7iCHA7xnd4REuCe2Q==,type:str]
    NC_dbpassword: ENC[AES256_GCM,data:n7Hfp+853pCwBAnkKDls0Xja1tR3wV789a45/1F7qizr2l1mglsmtdDm6aJ8o50H6igjHEM/ZeGVrLbwkop2uQ==,iv:bNs4idJdI5Qougs8Ac9JDdPxMzHcHwHoSBMmZeP2hI4=,tag:fwo4GVrwFeAq8xUYIj7HHg==,type:str]
    NC_passwordsalt: ENC[AES256_GCM,data:Hmx6tz6+Z/dox6iBAbumqSqePp/oeGtqAop2h2CM,iv:3GW+hdTIQGIilrTcMQ0868twAg5uVxQ0Xqj+VV4jq9w=,tag:uiX/u6mIDEWLtoUIqubsHw==,type:str]
    NC_secret: ENC[AES256_GCM,data:SlgpqmCgFzbtYRROivTEAe4PzEE2j84hO/Hgyl1XzwbsnNBmThgEuCzEq3vnzsUn,iv:N6jT8h/uc/BivtZIQGey6uEDITRazluDDirpB20xjOg=,tag:hK2fpgnpKimLF0a2475yag==,type:str]
    NC_instanceid: ENC[AES256_GCM,data:sCbr2taOaGz58YEA,iv:XcbaeU8iT78sUpQXO0ZQB+XtC71Cdk6MFs6fzRG6BsY=,tag:k9ra02Cgt42Pd1oDB0jdwQ==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhazFFV2llRzNuZ043ZUlm
            MzZ0eC91djJxYURITkI4SXQ4TGN5N2g1SFFjCmRNanZpNFJWV2o2Q0lTbXg4eEFU
            enJFVEJzU1FUblJmbXhPQlBSb29GaDQKLS0tIE92endvNmlpREdXVzEvWE1kYno2
            amQxK0dKRDN3aEdGKzhXZG5DREhreVkKEce45VjYKJ5MAzT+3vS5OBZ491N/I8Z5
            u3gWxe3sR3bobuMOyhFALQtRVL1wotP82Exfs/dVonDa/AXVf+FwGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T09:36:55Z"
    mac: ENC[AES256_GCM,data:fWrZOiECU0iMTSjDw+nI8FoPrRJu4DJ6n1pkmjhokkCW/Beu3GRpAUTE5XK5isNCJRHN+7ruhf5WCFjcytZnVKTbM427nvtTcZd3zpgtBGA7jJ4b6wn7WOofBfoCg0QhxLlXo/fhZJc9JIcV0D2Ery/2ITmN1TRh8L/CalozvBE=,iv:zHIuUfU5ym2jDbsu5c6iHpGN5sWtHLXAlp56D6pwhus=,tag:ueZX8R8uZmi5YntsZpVIQA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
