apiVersion: v1
kind: Secret
metadata:
    name: secret-env
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:JnTnpayYf10vK+1atWD3Nk6KWsM=,iv:4lRFDNfClcScNewrwP44lX1YNYDXtLKLJaXepT0Cli4=,tag:azGIMatW/E/ZOO1iKE115g==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:5hU0/psGn5Rdu+/Is+wrKFbHTieJH6+2YMBH/MLQcO/oQKunzPJtDA==,iv:p3L+6EnbDqt/tRHyoYSXE4TMDAA56l4cnxadtS3lDFg=,tag:4icInZ1/U3SRCFLJjOvlKg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:sf3TtVhixLhx3lEXpvu3pjqiPgUKV6nABHqvwSyKwtltukrczqR+vYY/4xT/7HxdOZRkh7OFOdRhaMHFKsE7fytEDb+7,iv:W569wFBHFFCIocOR6eyzPrLw7cXOEaimoXsfgfNZA+0=,tag:LtbBU5PW40gC5BlVrLPrhA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vw0+asN5UZ415idV5djelH3E3hTZujr81Yys0oMtgxijP8Z/QS/BMx1y5tthmjIYsIPrGDnHUxmeN1acRgkUhQ==,iv:V+ItyztHQ72Mn/xUq7L4YIbbQs3CfNluApeEYNGc/uk=,tag:UMaTKL+v9PF+Fv3LhrZTkA==,type:str]
    NEXTCLOUD_PASSWORDSALT: ENC[AES256_GCM,data:YalxXUkqt0pfDtvMTmVd1nrg4yOfftmUcaCsKt+o,iv:s2Mu3MaA2jZ8BdOm3OqCyt98m3/4NpSBXjdLI0OCBK8=,tag:dS5jZ1vhBLrfQJqvKeslIQ==,type:str]
    NEXTCLOUD_SECRET: ENC[AES256_GCM,data:cDXbKmMegkXNL1JHuNSA8ydBEyPa/gRpu4VMalJYzU4qFlr4bqhlzO9DYj52vDWF,iv:vc1IWOW8epDIwSohGMHO3BYvOITFhmwalQPsEcRZc0A=,tag:MNGt3G6tY0RE+smMWUWYAQ==,type:str]
    NEXTCLOUD_INSTANCEID: ENC[AES256_GCM,data:IP6WsS+M1bCCr6Xm,iv:WhLsHlCEj8jheYLX9hfxQvWnCUAzTBb/GSNY50UzqgY=,tag:Bcznw+HFjqSvxuXtN13HiQ==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dFVPSHRpRlpRalhOdnZB
            WEdHRURxR0VjdEprUkVMQmYzS3ZHTUNXV0hZCks3TzdXZVV6YnlzdU90NWpNMkVu
            M3E5WExFY0hqMDF1RnNwM0d4clhLQk0KLS0tIDJvRC9Uc3RkV1BMWFpPSTdPT0da
            ODZJakNjVWliTVdZNS82VUNhT0lvS0EK6H0ODPYHMQAy19152TWtlPuQpjtPF4d2
            fzuIpMS30OrX6ExfefzW0zXOmeVZqkW6yCDZciaGSDZZKA/M4inmwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T14:05:49Z"
    mac: ENC[AES256_GCM,data:+NrmAuyFspG50g9sfLXob7P6A0qQKKFOuq1Biy6UQNrYF7m0rUfvYL9dA8GZ1dAF1l4GYKUmRHxIri22ZwOMAjBVwiFesXIYl6ytyBfD8eL9XuXJQY7/+dX0EYV3LUluL2EY+xZ/uq4fiWpzTvvon9wEY8BsEi1ws5cTg+IfPxU=,iv:lGAX+wpquAcFepsQ0K/ebGugfOM6/ckACWbBukrP2UI=,tag:35aa9iBi9LRiFpCLshrckw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
