apiVersion: v1
kind: Secret
metadata:
    name: valkey
stringData:
    default: ENC[AES256_GCM,data:3FoOOVI+PT4eJjH/Wu5D9aqzQ20RnBPP,iv:MAYnJHrMWMmLgAmc37KyVVrNHcF6zDIABdoEQLhm1QE=,tag:/vkjqhfWzvhaYAz9Wq/bFA==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTVk5ZlpTK0xqUkVUdnMw
            S1JrbTFHTm1DajlNekhFVVRNL2RISDRZM1FBCklVV2RaWVlGNWVZSDM5Wnk3SUNn
            eEFMVnFSMmdjK0l3K3FLRFdYdEVJdzQKLS0tIEQ2dURBTzRlb05oVUdiTXFtYURD
            SmxTREFQQWc1RytBNzZDZkdEU24wQ1kKWYdvZUGMAcMVFVjgyWlziZwY/rerpi7R
            SG4fJt+4Yvbyjwb6EZDv05Q4pgLKSiZPMxxiMkC1dsz9iIDOY5PVMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:17:52Z"
    mac: ENC[AES256_GCM,data:2Nb7z+yaKN3DvgBKnEbMglAG9nrgwVDSo17dOrbD/CBm6FHbZ0Gm5TjqWbP/2hY3qN8wIAzgyb/tzA9hROHximREvhw6UMgA3TyT5sTB3Ipmvshe9gKcPg/EFg0Eng5z9SJ+GibSwFp2mlIJBOdIE4ZHJOTr0TPLLrzbJh4YknE=,iv:1pLdiAEsOy2GRNUKJh1kcuGRW6c/hV4UdKjWGHVImfE=,tag:AleCPEiKzkLYt0IHYIkD6Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
