apiVersion: v1
kind: Secret
metadata:
    name: anke-to-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    MARIADB_PASSWORD: ENC[AES256_GCM,data:IqL7Dt7NuAK4dabvb2oM6uSAZ0E2ccs/bYjYdnN+GNM=,iv:c5XE4KBpAf1PdLtAIUZhaa2bMy3WF1JAx7z9TXWmYZE=,tag:lzufN13LPWzgC/Dl//MRWQ==,type:str]
    TRAQ_WEBHOOK_ID: ENC[AES256_GCM,data:LM20cSozKNXw0OZmOnCNzwQDthLpwmfyeXTo/vNNthoH6oDD,iv:hrLOf7pvPmOIzDjMe8DOSK4YVivoNKlt5+cUFmrDlyA=,tag:CbnGA2BvF4GRXk/n42JC8Q==,type:str]
    TRAQ_WEBHOOK_SECRET: ENC[AES256_GCM,data:ZA+qrIhWXVJ2b7VDKiv5ASfsfFc=,iv:QmDVW0JbuxOYZGnzpENbX7W0vjdOsBw4/c5sQNv2pLY=,tag:Ht/hqH/bNu2Swk22PeQelQ==,type:str]
    TRAQ_BOT_TOKEN: ENC[AES256_GCM,data:m7Yy8WCgM76+Pze9xZAXjKKZnqZm3rsF8NOpM/DseQQSH9r/,iv:gxaM064gX5DJFHAf4lCuUmzTtgQFLb8bL3bNBEthmSQ=,tag:nj+sAP4g6i84fwYJqHq2jQ==,type:str]
sops:
    age:
        - recipient: age156red4ptw5huzpwlfnrukg4htuucdweu9jg8usjz98ggmeyedces3xqplq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnem5qL3UxY2tjaGZJemZk
            SkYzUkd0QTBBd1plNk0yS1l3WExBMWlYdHg4Ci9GekdyR3pMTXdRMGROaVBTZ20w
            SE1hbzRsd1RXQnVCV0Y0TGdvbnRTRHMKLS0tIElRYkRyb1U1NEJtMU1UVDd2KzMy
            L0pUYnZoR0J1STJ1T0k3blg2Q2lCdHMKVQ+e7wM1NMUtjeZPU3d2B8SgBuoIZ4P8
            L/DS9o9Q89ighEO3a37izRMyh/vis1Xcc5UxsAxzmxZGUKNwGNkw8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T05:47:08Z"
    mac: ENC[AES256_GCM,data:7FxjKahIUO4ds9DRujXLv1/gFSByvbvHUdtYJWkvHeboXaZBXH26+f2UsgCCXs0bnNLHDpYWBVOckV1c4X4G/JMgdZBTNymQobAe9BoKrSZOPI/yKjOGQqG4FZrFc8SwvO645Qpq7uW5z0ooR4VQhgQMJ4UhHKGZiijKlYyorAk=,iv:SN0QMTWlWWVKIUQBflH/3uZBSPpa6m/95LK6rC4mgXw=,tag:vCPZ0dXW/YSZOMe8gaABHg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
